#!/usr/bin/env node
// vim: set ft=javascript :

var fs = require("fs");
var child_process = require("child_process");

var Class = require("../../lib/Class");
eval(Class.$import("../../lib/compiler"));

"use strict";

var NodePlatform = Platform.extend({
	load: function(filename) {
		//var buff = fs.readFileSync(filename).toString();
		//return buff.replace(/^\#\![^\n]*/, "");
		return fs.readFileSync(filename).toString();
	}
});

function main(args) {
	var platform = new NodePlatform();
	var compiler = new Compiler(platform);

	compiler.addSourceFile("lib/test.jsx");
	compiler.addSourceFile(args[0]);

	if(!compiler.compile()) {
		process.exit(1);
	}

	var output = compiler.getOutput();
	output += "(new Test$()).run$();";

	console.log( output.replace(/^/mg, "#") );

	var child = child_process.spawn(process.execPath, ["/dev/stdin"]);

	child.stdin.write(output);
	child.stdin.end();

	child.stdout.on("data", function (data) {
		process.stdout.write(data);
	});
	child.stderr.on("data", function (data) {
		process.stderr.write(data);
	});
	child.on("exit", function (status) {
		process.exit(status);
	});
}

main(process.argv.slice(2));

