// THIS FILE IS AUTOMATICALLY GENERATED.
/**

Document Object Model Level 3 Core

Specification:
    http://www.w3.org/TR/DOM-Level-3-Core/
*/

/*
automatically generated from:
	http://www.w3.org/TR/DOM-Level-3-Core/idl/dom.idl
*/
native class NameList {

	function getName(
		index : int/*unsigned long*/
	) : string/*DOMString*/;
	function getNamespaceURI(
		index : int/*unsigned long*/
	) : string/*DOMString*/;
	__readonly__ var length : int/*unsigned long*/;
	function contains(str : string/*DOMString*/) : boolean;
	function containsNS(
		namespaceURI : string/*DOMString*/,
		name : string/*DOMString*/
	) : boolean;

} // end of NameList

native class DOMImplementationList {

	function item(index : int/*unsigned long*/) : DOMImplementation;
	__readonly__ var length : int/*unsigned long*/;

} // end of DOMImplementationList

native class DOMImplementationSource {

	function getDOMImplementation(
		features : string/*DOMString*/
	) : DOMImplementation;
	function getDOMImplementationList(
		features : string/*DOMString*/
	) : DOMImplementationList;

} // end of DOMImplementationSource

native class NamedNodeMap {

	function getNamedItem(name : string/*DOMString*/) : Node;
	function setNamedItem(arg : Node) : Node;
	function removeNamedItem(name : string/*DOMString*/) : Node;
	function item(index : int/*unsigned long*/) : Node;
	__readonly__ var length : int/*unsigned long*/;
	// Introduced in DOM Level 2:
	function getNamedItemNS(
		namespaceURI : string/*DOMString*/,
		localName : string/*DOMString*/
	) : Node;
	// Introduced in DOM Level 2:
	function setNamedItemNS(arg : Node) : Node;
	// Introduced in DOM Level 2:
	function removeNamedItemNS(
		namespaceURI : string/*DOMString*/,
		localName : string/*DOMString*/
	) : Node;

} // end of NamedNodeMap

native __fake__ class TypeInfo {

	__readonly__ var typeName : string/*DOMString*/;
	__readonly__ var typeNamespace : string/*DOMString*/;
	// DerivationMethods
	static const     DERIVATION_RESTRICTION : int/*unsigned long*/;
	__readonly__ var DERIVATION_RESTRICTION : int/*unsigned long*/;
	static const     DERIVATION_EXTENSION : int/*unsigned long*/;
	__readonly__ var DERIVATION_EXTENSION : int/*unsigned long*/;
	static const     DERIVATION_UNION : int/*unsigned long*/;
	__readonly__ var DERIVATION_UNION : int/*unsigned long*/;
	static const     DERIVATION_LIST : int/*unsigned long*/;
	__readonly__ var DERIVATION_LIST : int/*unsigned long*/;
	function isDerivedFrom(
		typeNamespaceArg : string/*DOMString*/,
		typeNameArg : string/*DOMString*/,
		derivationMethod : int/*unsigned long*/
	) : boolean;

} // end of TypeInfo

native __fake__ class DOMLocator {

	__readonly__ var lineNumber : int/*long*/;
	__readonly__ var columnNumber : int/*long*/;
	__readonly__ var byteOffset : int/*long*/;
	__readonly__ var utf16Offset : int/*long*/;
	__readonly__ var relatedNode : Node;
	__readonly__ var uri : string/*DOMString*/;

} // end of DOMLocator

native __fake__ class DOMConfiguration {

	function setParameter(
		name : string/*DOMString*/,
		value : variant/*any*//*DOMUserData*/
	) : void;
	function getParameter(
		name : string/*DOMString*/
	) : variant/*any*//*DOMUserData*/;
	function canSetParameter(
		name : string/*DOMString*/,
		value : variant/*any*//*DOMUserData*/
	) : boolean;
	__readonly__ var parameterNames : DOMStringList;

} // end of DOMConfiguration

native class CDATASection extends Text {
}

native class Notation extends Node {

	__readonly__ var publicId : string/*DOMString*/;
	__readonly__ var systemId : string/*DOMString*/;

} // end of Notation

native class Entity extends Node {

	__readonly__ var publicId : string/*DOMString*/;
	__readonly__ var systemId : string/*DOMString*/;
	__readonly__ var notationName : string/*DOMString*/;
	// Introduced in DOM Level 3:
	__readonly__ var inputEncoding : string/*DOMString*/;
	// Introduced in DOM Level 3:
	__readonly__ var xmlEncoding : string/*DOMString*/;
	// Introduced in DOM Level 3:
	__readonly__ var xmlVersion : string/*DOMString*/;

} // end of Entity

native class EntityReference extends Node {
}

/*
end of generated files from:
	http://www.w3.org/TR/DOM-Level-3-Core/idl/dom.idl
*/

