// Chrome 23
// 
// document.getElementById("input").innerHTML = (function(style) { var a = []; for(var k in style) { if(typeof style[k] === "function") continue; a.push("attribute "+(typeof style[k])+"? "+k+";"+String.fromCharCode(0x0a)) }; return a.sort().join(""); }(document.body.style))
//

partial interface CSSStyleDeclaration {
    attribute number? length;
    attribute object? parentRule;
    attribute string? alignmentBaseline;
    attribute string? background;
    attribute string? backgroundAttachment;
    attribute string? backgroundClip;
    attribute string? backgroundColor;
    attribute string? backgroundImage;
    attribute string? backgroundOrigin;
    attribute string? backgroundPosition;
    attribute string? backgroundPositionX;
    attribute string? backgroundPositionY;
    attribute string? backgroundRepeat;
    attribute string? backgroundRepeatX;
    attribute string? backgroundRepeatY;
    attribute string? backgroundSize;
    attribute string? baselineShift;
    attribute string? border;
    attribute string? borderBottom;
    attribute string? borderBottomColor;
    attribute string? borderBottomLeftRadius;
    attribute string? borderBottomRightRadius;
    attribute string? borderBottomStyle;
    attribute string? borderBottomWidth;
    attribute string? borderCollapse;
    attribute string? borderColor;
    attribute string? borderImage;
    attribute string? borderImageOutset;
    attribute string? borderImageRepeat;
    attribute string? borderImageSlice;
    attribute string? borderImageSource;
    attribute string? borderImageWidth;
    attribute string? borderLeft;
    attribute string? borderLeftColor;
    attribute string? borderLeftStyle;
    attribute string? borderLeftWidth;
    attribute string? borderRadius;
    attribute string? borderRight;
    attribute string? borderRightColor;
    attribute string? borderRightStyle;
    attribute string? borderRightWidth;
    attribute string? borderSpacing;
    attribute string? borderStyle;
    attribute string? borderTop;
    attribute string? borderTopColor;
    attribute string? borderTopLeftRadius;
    attribute string? borderTopRightRadius;
    attribute string? borderTopStyle;
    attribute string? borderTopWidth;
    attribute string? borderWidth;
    attribute string? bottom;
    attribute string? boxShadow;
    attribute string? boxSizing;
    attribute string? captionSide;
    attribute string? clear;
    attribute string? clip;
    attribute string? clipPath;
    attribute string? clipRule;
    attribute string? color;
    attribute string? colorInterpolation;
    attribute string? colorInterpolationFilters;
    attribute string? colorProfile;
    attribute string? colorRendering;
    attribute string? content;
    attribute string? counterIncrement;
    attribute string? counterReset;
    attribute string? cssText;
    attribute string? cursor;
    attribute string? direction;
    attribute string? display;
    attribute string? dominantBaseline;
    attribute string? emptyCells;
    attribute string? enableBackground;
    attribute string? fill;
    attribute string? fillOpacity;
    attribute string? fillRule;
    attribute string? filter;
    attribute string? float;
    attribute string? floodColor;
    attribute string? floodOpacity;
    attribute string? font;
    attribute string? fontFamily;
    attribute string? fontSize;
    attribute string? fontStretch;
    attribute string? fontStyle;
    attribute string? fontVariant;
    attribute string? fontWeight;
    attribute string? glyphOrientationHorizontal;
    attribute string? glyphOrientationVertical;
    attribute string? height;
    attribute string? imageRendering;
    attribute string? kerning;
    attribute string? left;
    attribute string? letterSpacing;
    attribute string? lightingColor;
    attribute string? lineHeight;
    attribute string? listStyle;
    attribute string? listStyleImage;
    attribute string? listStylePosition;
    attribute string? listStyleType;
    attribute string? margin;
    attribute string? marginBottom;
    attribute string? marginLeft;
    attribute string? marginRight;
    attribute string? marginTop;
    attribute string? marker;
    attribute string? markerEnd;
    attribute string? markerMid;
    attribute string? markerStart;
    attribute string? mask;
    attribute string? maxHeight;
    attribute string? maxWidth;
    attribute string? minHeight;
    attribute string? minWidth;
    attribute string? opacity;
    attribute string? orphans;
    attribute string? outline;
    attribute string? outlineColor;
    attribute string? outlineOffset;
    attribute string? outlineStyle;
    attribute string? outlineWidth;
    attribute string? overflow;
    attribute string? overflowWrap;
    attribute string? overflowX;
    attribute string? overflowY;
    attribute string? padding;
    attribute string? paddingBottom;
    attribute string? paddingLeft;
    attribute string? paddingRight;
    attribute string? paddingTop;
    attribute string? page;
    attribute string? pageBreakAfter;
    attribute string? pageBreakBefore;
    attribute string? pageBreakInside;
    attribute string? pointerEvents;
    attribute string? position;
    attribute string? quotes;
    attribute string? resize;
    attribute string? right;
    attribute string? shapeRendering;
    attribute string? size;
    attribute string? speak;
    attribute string? src;
    attribute string? stopColor;
    attribute string? stopOpacity;
    attribute string? stroke;
    attribute string? strokeDasharray;
    attribute string? strokeDashoffset;
    attribute string? strokeLinecap;
    attribute string? strokeLinejoin;
    attribute string? strokeMiterlimit;
    attribute string? strokeOpacity;
    attribute string? strokeWidth;
    attribute string? tabSize;
    attribute string? tableLayout;
    attribute string? textAlign;
    attribute string? textAnchor;
    attribute string? textDecoration;
    attribute string? textIndent;
    attribute string? textLineThrough;
    attribute string? textLineThroughColor;
    attribute string? textLineThroughMode;
    attribute string? textLineThroughStyle;
    attribute string? textLineThroughWidth;
    attribute string? textOverflow;
    attribute string? textOverline;
    attribute string? textOverlineColor;
    attribute string? textOverlineMode;
    attribute string? textOverlineStyle;
    attribute string? textOverlineWidth;
    attribute string? textRendering;
    attribute string? textShadow;
    attribute string? textTransform;
    attribute string? textUnderline;
    attribute string? textUnderlineColor;
    attribute string? textUnderlineMode;
    attribute string? textUnderlineStyle;
    attribute string? textUnderlineWidth;
    attribute string? top;
    attribute string? unicodeBidi;
    attribute string? unicodeRange;
    attribute string? vectorEffect;
    attribute string? verticalAlign;
    attribute string? visibility;
    attribute string? webkitAlignContent;
    attribute string? webkitAlignItems;
    attribute string? webkitAlignSelf;
    attribute string? webkitAnimation;
    attribute string? webkitAnimationDelay;
    attribute string? webkitAnimationDirection;
    attribute string? webkitAnimationDuration;
    attribute string? webkitAnimationFillMode;
    attribute string? webkitAnimationIterationCount;
    attribute string? webkitAnimationName;
    attribute string? webkitAnimationPlayState;
    attribute string? webkitAnimationTimingFunction;
    attribute string? webkitAppearance;
    attribute string? webkitAspectRatio;
    attribute string? webkitBackfaceVisibility;
    attribute string? webkitBackgroundClip;
    attribute string? webkitBackgroundComposite;
    attribute string? webkitBackgroundOrigin;
    attribute string? webkitBackgroundSize;
    attribute string? webkitBorderAfter;
    attribute string? webkitBorderAfterColor;
    attribute string? webkitBorderAfterStyle;
    attribute string? webkitBorderAfterWidth;
    attribute string? webkitBorderBefore;
    attribute string? webkitBorderBeforeColor;
    attribute string? webkitBorderBeforeStyle;
    attribute string? webkitBorderBeforeWidth;
    attribute string? webkitBorderEnd;
    attribute string? webkitBorderEndColor;
    attribute string? webkitBorderEndStyle;
    attribute string? webkitBorderEndWidth;
    attribute string? webkitBorderFit;
    attribute string? webkitBorderHorizontalSpacing;
    attribute string? webkitBorderImage;
    attribute string? webkitBorderRadius;
    attribute string? webkitBorderStart;
    attribute string? webkitBorderStartColor;
    attribute string? webkitBorderStartStyle;
    attribute string? webkitBorderStartWidth;
    attribute string? webkitBorderVerticalSpacing;
    attribute string? webkitBoxAlign;
    attribute string? webkitBoxDecorationBreak;
    attribute string? webkitBoxDirection;
    attribute string? webkitBoxFlex;
    attribute string? webkitBoxFlexGroup;
    attribute string? webkitBoxLines;
    attribute string? webkitBoxOrdinalGroup;
    attribute string? webkitBoxOrient;
    attribute string? webkitBoxPack;
    attribute string? webkitBoxReflect;
    attribute string? webkitBoxShadow;
    attribute string? webkitClipPath;
    attribute string? webkitColorCorrection;
    attribute string? webkitColumnAxis;
    attribute string? webkitColumnBreakAfter;
    attribute string? webkitColumnBreakBefore;
    attribute string? webkitColumnBreakInside;
    attribute string? webkitColumnCount;
    attribute string? webkitColumnGap;
    attribute string? webkitColumnProgression;
    attribute string? webkitColumnRule;
    attribute string? webkitColumnRuleColor;
    attribute string? webkitColumnRuleStyle;
    attribute string? webkitColumnRuleWidth;
    attribute string? webkitColumnSpan;
    attribute string? webkitColumnWidth;
    attribute string? webkitColumns;
    attribute string? webkitFilter;
    attribute string? webkitFlex;
    attribute string? webkitFlexBasis;
    attribute string? webkitFlexDirection;
    attribute string? webkitFlexFlow;
    attribute string? webkitFlexGrow;
    attribute string? webkitFlexShrink;
    attribute string? webkitFlexWrap;
    attribute string? webkitFlowFrom;
    attribute string? webkitFlowInto;
    attribute string? webkitFontFeatureSettings;
    attribute string? webkitFontKerning;
    attribute string? webkitFontSizeDelta;
    attribute string? webkitFontSmoothing;
    attribute string? webkitFontVariantLigatures;
    attribute string? webkitGridColumn;
    attribute string? webkitGridColumns;
    attribute string? webkitGridRow;
    attribute string? webkitGridRows;
    attribute string? webkitHighlight;
    attribute string? webkitHyphenateCharacter;
    attribute string? webkitHyphenateLimitAfter;
    attribute string? webkitHyphenateLimitBefore;
    attribute string? webkitHyphenateLimitLines;
    attribute string? webkitHyphens;
    attribute string? webkitJustifyContent;
    attribute string? webkitLineAlign;
    attribute string? webkitLineBoxContain;
    attribute string? webkitLineBreak;
    attribute string? webkitLineClamp;
    attribute string? webkitLineGrid;
    attribute string? webkitLineSnap;
    attribute string? webkitLocale;
    attribute string? webkitLogicalHeight;
    attribute string? webkitLogicalWidth;
    attribute string? webkitMarginAfter;
    attribute string? webkitMarginAfterCollapse;
    attribute string? webkitMarginBefore;
    attribute string? webkitMarginBeforeCollapse;
    attribute string? webkitMarginBottomCollapse;
    attribute string? webkitMarginCollapse;
    attribute string? webkitMarginEnd;
    attribute string? webkitMarginStart;
    attribute string? webkitMarginTopCollapse;
    attribute string? webkitMarquee;
    attribute string? webkitMarqueeDirection;
    attribute string? webkitMarqueeIncrement;
    attribute string? webkitMarqueeRepetition;
    attribute string? webkitMarqueeSpeed;
    attribute string? webkitMarqueeStyle;
    attribute string? webkitMask;
    attribute string? webkitMaskAttachment;
    attribute string? webkitMaskBoxImage;
    attribute string? webkitMaskBoxImageOutset;
    attribute string? webkitMaskBoxImageRepeat;
    attribute string? webkitMaskBoxImageSlice;
    attribute string? webkitMaskBoxImageSource;
    attribute string? webkitMaskBoxImageWidth;
    attribute string? webkitMaskClip;
    attribute string? webkitMaskComposite;
    attribute string? webkitMaskImage;
    attribute string? webkitMaskOrigin;
    attribute string? webkitMaskPosition;
    attribute string? webkitMaskPositionX;
    attribute string? webkitMaskPositionY;
    attribute string? webkitMaskRepeat;
    attribute string? webkitMaskRepeatX;
    attribute string? webkitMaskRepeatY;
    attribute string? webkitMaskSize;
    attribute string? webkitMaxLogicalHeight;
    attribute string? webkitMaxLogicalWidth;
    attribute string? webkitMinLogicalHeight;
    attribute string? webkitMinLogicalWidth;
    attribute string? webkitNbspMode;
    attribute string? webkitOrder;
    attribute string? webkitPaddingAfter;
    attribute string? webkitPaddingBefore;
    attribute string? webkitPaddingEnd;
    attribute string? webkitPaddingStart;
    attribute string? webkitPerspective;
    attribute string? webkitPerspectiveOrigin;
    attribute string? webkitPerspectiveOriginX;
    attribute string? webkitPerspectiveOriginY;
    attribute string? webkitPrintColorAdjust;
    attribute string? webkitRegionBreakAfter;
    attribute string? webkitRegionBreakBefore;
    attribute string? webkitRegionBreakInside;
    attribute string? webkitRegionOverflow;
    attribute string? webkitRtlOrdering;
    attribute string? webkitShapeInside;
    attribute string? webkitShapeOutside;
    attribute string? webkitSvgShadow;
    attribute string? webkitTapHighlightColor;
    attribute string? webkitTextCombine;
    attribute string? webkitTextDecorationsInEffect;
    attribute string? webkitTextEmphasis;
    attribute string? webkitTextEmphasisColor;
    attribute string? webkitTextEmphasisPosition;
    attribute string? webkitTextEmphasisStyle;
    attribute string? webkitTextFillColor;
    attribute string? webkitTextOrientation;
    attribute string? webkitTextSecurity;
    attribute string? webkitTextSizeAdjust;
    attribute string? webkitTextStroke;
    attribute string? webkitTextStrokeColor;
    attribute string? webkitTextStrokeWidth;
    attribute string? webkitTransform;
    attribute string? webkitTransformOrigin;
    attribute string? webkitTransformOriginX;
    attribute string? webkitTransformOriginY;
    attribute string? webkitTransformOriginZ;
    attribute string? webkitTransformStyle;
    attribute string? webkitTransition;
    attribute string? webkitTransitionDelay;
    attribute string? webkitTransitionDuration;
    attribute string? webkitTransitionProperty;
    attribute string? webkitTransitionTimingFunction;
    attribute string? webkitUserDrag;
    attribute string? webkitUserModify;
    attribute string? webkitUserSelect;
    attribute string? webkitWidgetRegion;
    attribute string? webkitWrap;
    attribute string? webkitWrapFlow;
    attribute string? webkitWrapMargin;
    attribute string? webkitWrapPadding;
    attribute string? webkitWrapThrough;
    attribute string? webkitWritingMode;
    attribute string? whiteSpace;
    attribute string? widows;
    attribute string? width;
    attribute string? wordBreak;
    attribute string? wordSpacing;
    attribute string? wordWrap;
    attribute string? writingMode;
    attribute string? zIndex;
    attribute string? zoom;
};

