// Chrome 19
// 
// document.getElementById("input").innerHTML = (function(style) { var a = []; for(var k in style) { if(typeof style[k] === "function") continue; a.push("attribute Maybe<"+(typeof style[k])+"> "+k+";"+String.fromCharCode(0x0a)) }; return a.sort().join(""); }(document.body.style))
//

partial interface CSSStyleDeclaration {
    attribute Maybe<number> length;
    attribute Maybe<object> parentRule;
    attribute Maybe<string> alignmentBaseline;
    attribute Maybe<string> background;
    attribute Maybe<string> backgroundAttachment;
    attribute Maybe<string> backgroundClip;
    attribute Maybe<string> backgroundColor;
    attribute Maybe<string> backgroundImage;
    attribute Maybe<string> backgroundOrigin;
    attribute Maybe<string> backgroundPosition;
    attribute Maybe<string> backgroundPositionX;
    attribute Maybe<string> backgroundPositionY;
    attribute Maybe<string> backgroundRepeat;
    attribute Maybe<string> backgroundRepeatX;
    attribute Maybe<string> backgroundRepeatY;
    attribute Maybe<string> backgroundSize;
    attribute Maybe<string> baselineShift;
    attribute Maybe<string> border;
    attribute Maybe<string> borderBottom;
    attribute Maybe<string> borderBottomColor;
    attribute Maybe<string> borderBottomLeftRadius;
    attribute Maybe<string> borderBottomRightRadius;
    attribute Maybe<string> borderBottomStyle;
    attribute Maybe<string> borderBottomWidth;
    attribute Maybe<string> borderCollapse;
    attribute Maybe<string> borderColor;
    attribute Maybe<string> borderImage;
    attribute Maybe<string> borderImageOutset;
    attribute Maybe<string> borderImageRepeat;
    attribute Maybe<string> borderImageSlice;
    attribute Maybe<string> borderImageSource;
    attribute Maybe<string> borderImageWidth;
    attribute Maybe<string> borderLeft;
    attribute Maybe<string> borderLeftColor;
    attribute Maybe<string> borderLeftStyle;
    attribute Maybe<string> borderLeftWidth;
    attribute Maybe<string> borderRadius;
    attribute Maybe<string> borderRight;
    attribute Maybe<string> borderRightColor;
    attribute Maybe<string> borderRightStyle;
    attribute Maybe<string> borderRightWidth;
    attribute Maybe<string> borderSpacing;
    attribute Maybe<string> borderStyle;
    attribute Maybe<string> borderTop;
    attribute Maybe<string> borderTopColor;
    attribute Maybe<string> borderTopLeftRadius;
    attribute Maybe<string> borderTopRightRadius;
    attribute Maybe<string> borderTopStyle;
    attribute Maybe<string> borderTopWidth;
    attribute Maybe<string> borderWidth;
    attribute Maybe<string> bottom;
    attribute Maybe<string> boxShadow;
    attribute Maybe<string> boxSizing;
    attribute Maybe<string> captionSide;
    attribute Maybe<string> clear;
    attribute Maybe<string> clip;
    attribute Maybe<string> clipPath;
    attribute Maybe<string> clipRule;
    attribute Maybe<string> color;
    attribute Maybe<string> colorInterpolation;
    attribute Maybe<string> colorInterpolationFilters;
    attribute Maybe<string> colorProfile;
    attribute Maybe<string> colorRendering;
    attribute Maybe<string> content;
    attribute Maybe<string> counterIncrement;
    attribute Maybe<string> counterReset;
    attribute Maybe<string> cssText;
    attribute Maybe<string> cursor;
    attribute Maybe<string> direction;
    attribute Maybe<string> display;
    attribute Maybe<string> dominantBaseline;
    attribute Maybe<string> emptyCells;
    attribute Maybe<string> enableBackground;
    attribute Maybe<string> fill;
    attribute Maybe<string> fillOpacity;
    attribute Maybe<string> fillRule;
    attribute Maybe<string> filter;
    attribute Maybe<string> float;
    attribute Maybe<string> floodColor;
    attribute Maybe<string> floodOpacity;
    attribute Maybe<string> font;
    attribute Maybe<string> fontFamily;
    attribute Maybe<string> fontSize;
    attribute Maybe<string> fontStretch;
    attribute Maybe<string> fontStyle;
    attribute Maybe<string> fontVariant;
    attribute Maybe<string> fontWeight;
    attribute Maybe<string> glyphOrientationHorizontal;
    attribute Maybe<string> glyphOrientationVertical;
    attribute Maybe<string> height;
    attribute Maybe<string> imageRendering;
    attribute Maybe<string> kerning;
    attribute Maybe<string> left;
    attribute Maybe<string> letterSpacing;
    attribute Maybe<string> lightingColor;
    attribute Maybe<string> lineHeight;
    attribute Maybe<string> listStyle;
    attribute Maybe<string> listStyleImage;
    attribute Maybe<string> listStylePosition;
    attribute Maybe<string> listStyleType;
    attribute Maybe<string> margin;
    attribute Maybe<string> marginBottom;
    attribute Maybe<string> marginLeft;
    attribute Maybe<string> marginRight;
    attribute Maybe<string> marginTop;
    attribute Maybe<string> marker;
    attribute Maybe<string> markerEnd;
    attribute Maybe<string> markerMid;
    attribute Maybe<string> markerStart;
    attribute Maybe<string> mask;
    attribute Maybe<string> maxHeight;
    attribute Maybe<string> maxWidth;
    attribute Maybe<string> minHeight;
    attribute Maybe<string> minWidth;
    attribute Maybe<string> opacity;
    attribute Maybe<string> orphans;
    attribute Maybe<string> outline;
    attribute Maybe<string> outlineColor;
    attribute Maybe<string> outlineOffset;
    attribute Maybe<string> outlineStyle;
    attribute Maybe<string> outlineWidth;
    attribute Maybe<string> overflow;
    attribute Maybe<string> overflowX;
    attribute Maybe<string> overflowY;
    attribute Maybe<string> padding;
    attribute Maybe<string> paddingBottom;
    attribute Maybe<string> paddingLeft;
    attribute Maybe<string> paddingRight;
    attribute Maybe<string> paddingTop;
    attribute Maybe<string> page;
    attribute Maybe<string> pageBreakAfter;
    attribute Maybe<string> pageBreakBefore;
    attribute Maybe<string> pageBreakInside;
    attribute Maybe<string> pointerEvents;
    attribute Maybe<string> position;
    attribute Maybe<string> quotes;
    attribute Maybe<string> resize;
    attribute Maybe<string> right;
    attribute Maybe<string> shapeRendering;
    attribute Maybe<string> size;
    attribute Maybe<string> speak;
    attribute Maybe<string> src;
    attribute Maybe<string> stopColor;
    attribute Maybe<string> stopOpacity;
    attribute Maybe<string> stroke;
    attribute Maybe<string> strokeDasharray;
    attribute Maybe<string> strokeDashoffset;
    attribute Maybe<string> strokeLinecap;
    attribute Maybe<string> strokeLinejoin;
    attribute Maybe<string> strokeMiterlimit;
    attribute Maybe<string> strokeOpacity;
    attribute Maybe<string> strokeWidth;
    attribute Maybe<string> tableLayout;
    attribute Maybe<string> textAlign;
    attribute Maybe<string> textAnchor;
    attribute Maybe<string> textDecoration;
    attribute Maybe<string> textIndent;
    attribute Maybe<string> textLineThrough;
    attribute Maybe<string> textLineThroughColor;
    attribute Maybe<string> textLineThroughMode;
    attribute Maybe<string> textLineThroughStyle;
    attribute Maybe<string> textLineThroughWidth;
    attribute Maybe<string> textOverflow;
    attribute Maybe<string> textOverline;
    attribute Maybe<string> textOverlineColor;
    attribute Maybe<string> textOverlineMode;
    attribute Maybe<string> textOverlineStyle;
    attribute Maybe<string> textOverlineWidth;
    attribute Maybe<string> textRendering;
    attribute Maybe<string> textShadow;
    attribute Maybe<string> textTransform;
    attribute Maybe<string> textUnderline;
    attribute Maybe<string> textUnderlineColor;
    attribute Maybe<string> textUnderlineMode;
    attribute Maybe<string> textUnderlineStyle;
    attribute Maybe<string> textUnderlineWidth;
    attribute Maybe<string> top;
    attribute Maybe<string> unicodeBidi;
    attribute Maybe<string> unicodeRange;
    attribute Maybe<string> vectorEffect;
    attribute Maybe<string> verticalAlign;
    attribute Maybe<string> visibility;
    attribute Maybe<string> webkitAnimation;
    attribute Maybe<string> webkitAnimationDelay;
    attribute Maybe<string> webkitAnimationDirection;
    attribute Maybe<string> webkitAnimationDuration;
    attribute Maybe<string> webkitAnimationFillMode;
    attribute Maybe<string> webkitAnimationIterationCount;
    attribute Maybe<string> webkitAnimationName;
    attribute Maybe<string> webkitAnimationPlayState;
    attribute Maybe<string> webkitAnimationTimingFunction;
    attribute Maybe<string> webkitAppearance;
    attribute Maybe<string> webkitAspectRatio;
    attribute Maybe<string> webkitBackfaceVisibility;
    attribute Maybe<string> webkitBackgroundClip;
    attribute Maybe<string> webkitBackgroundComposite;
    attribute Maybe<string> webkitBackgroundOrigin;
    attribute Maybe<string> webkitBackgroundSize;
    attribute Maybe<string> webkitBorderAfter;
    attribute Maybe<string> webkitBorderAfterColor;
    attribute Maybe<string> webkitBorderAfterStyle;
    attribute Maybe<string> webkitBorderAfterWidth;
    attribute Maybe<string> webkitBorderBefore;
    attribute Maybe<string> webkitBorderBeforeColor;
    attribute Maybe<string> webkitBorderBeforeStyle;
    attribute Maybe<string> webkitBorderBeforeWidth;
    attribute Maybe<string> webkitBorderEnd;
    attribute Maybe<string> webkitBorderEndColor;
    attribute Maybe<string> webkitBorderEndStyle;
    attribute Maybe<string> webkitBorderEndWidth;
    attribute Maybe<string> webkitBorderFit;
    attribute Maybe<string> webkitBorderHorizontalSpacing;
    attribute Maybe<string> webkitBorderImage;
    attribute Maybe<string> webkitBorderRadius;
    attribute Maybe<string> webkitBorderStart;
    attribute Maybe<string> webkitBorderStartColor;
    attribute Maybe<string> webkitBorderStartStyle;
    attribute Maybe<string> webkitBorderStartWidth;
    attribute Maybe<string> webkitBorderVerticalSpacing;
    attribute Maybe<string> webkitBoxAlign;
    attribute Maybe<string> webkitBoxDirection;
    attribute Maybe<string> webkitBoxFlex;
    attribute Maybe<string> webkitBoxFlexGroup;
    attribute Maybe<string> webkitBoxLines;
    attribute Maybe<string> webkitBoxOrdinalGroup;
    attribute Maybe<string> webkitBoxOrient;
    attribute Maybe<string> webkitBoxPack;
    attribute Maybe<string> webkitBoxReflect;
    attribute Maybe<string> webkitBoxShadow;
    attribute Maybe<string> webkitColorCorrection;
    attribute Maybe<string> webkitColumnAxis;
    attribute Maybe<string> webkitColumnBreakAfter;
    attribute Maybe<string> webkitColumnBreakBefore;
    attribute Maybe<string> webkitColumnBreakInside;
    attribute Maybe<string> webkitColumnCount;
    attribute Maybe<string> webkitColumnGap;
    attribute Maybe<string> webkitColumnRule;
    attribute Maybe<string> webkitColumnRuleColor;
    attribute Maybe<string> webkitColumnRuleStyle;
    attribute Maybe<string> webkitColumnRuleWidth;
    attribute Maybe<string> webkitColumnSpan;
    attribute Maybe<string> webkitColumnWidth;
    attribute Maybe<string> webkitColumns;
    attribute Maybe<string> webkitFilter;
    attribute Maybe<string> webkitFlexAlign;
    attribute Maybe<string> webkitFlexDirection;
    attribute Maybe<string> webkitFlexFlow;
    attribute Maybe<string> webkitFlexItemAlign;
    attribute Maybe<string> webkitFlexLinePack;
    attribute Maybe<string> webkitFlexOrder;
    attribute Maybe<string> webkitFlexPack;
    attribute Maybe<string> webkitFlexWrap;
    attribute Maybe<string> webkitFlowFrom;
    attribute Maybe<string> webkitFlowInto;
    attribute Maybe<string> webkitFontFeatureSettings;
    attribute Maybe<string> webkitFontKerning;
    attribute Maybe<string> webkitFontSizeDelta;
    attribute Maybe<string> webkitFontSmoothing;
    attribute Maybe<string> webkitFontVariantLigatures;
    attribute Maybe<string> webkitHighlight;
    attribute Maybe<string> webkitHyphenateCharacter;
    attribute Maybe<string> webkitHyphenateLimitAfter;
    attribute Maybe<string> webkitHyphenateLimitBefore;
    attribute Maybe<string> webkitHyphenateLimitLines;
    attribute Maybe<string> webkitHyphens;
    attribute Maybe<string> webkitLineAlign;
    attribute Maybe<string> webkitLineBoxContain;
    attribute Maybe<string> webkitLineBreak;
    attribute Maybe<string> webkitLineClamp;
    attribute Maybe<string> webkitLineGrid;
    attribute Maybe<string> webkitLineSnap;
    attribute Maybe<string> webkitLocale;
    attribute Maybe<string> webkitLogicalHeight;
    attribute Maybe<string> webkitLogicalWidth;
    attribute Maybe<string> webkitMarginAfter;
    attribute Maybe<string> webkitMarginAfterCollapse;
    attribute Maybe<string> webkitMarginBefore;
    attribute Maybe<string> webkitMarginBeforeCollapse;
    attribute Maybe<string> webkitMarginBottomCollapse;
    attribute Maybe<string> webkitMarginCollapse;
    attribute Maybe<string> webkitMarginEnd;
    attribute Maybe<string> webkitMarginStart;
    attribute Maybe<string> webkitMarginTopCollapse;
    attribute Maybe<string> webkitMarquee;
    attribute Maybe<string> webkitMarqueeDirection;
    attribute Maybe<string> webkitMarqueeIncrement;
    attribute Maybe<string> webkitMarqueeRepetition;
    attribute Maybe<string> webkitMarqueeSpeed;
    attribute Maybe<string> webkitMarqueeStyle;
    attribute Maybe<string> webkitMask;
    attribute Maybe<string> webkitMaskAttachment;
    attribute Maybe<string> webkitMaskBoxImage;
    attribute Maybe<string> webkitMaskBoxImageOutset;
    attribute Maybe<string> webkitMaskBoxImageRepeat;
    attribute Maybe<string> webkitMaskBoxImageSlice;
    attribute Maybe<string> webkitMaskBoxImageSource;
    attribute Maybe<string> webkitMaskBoxImageWidth;
    attribute Maybe<string> webkitMaskClip;
    attribute Maybe<string> webkitMaskComposite;
    attribute Maybe<string> webkitMaskImage;
    attribute Maybe<string> webkitMaskOrigin;
    attribute Maybe<string> webkitMaskPosition;
    attribute Maybe<string> webkitMaskPositionX;
    attribute Maybe<string> webkitMaskPositionY;
    attribute Maybe<string> webkitMaskRepeat;
    attribute Maybe<string> webkitMaskRepeatX;
    attribute Maybe<string> webkitMaskRepeatY;
    attribute Maybe<string> webkitMaskSize;
    attribute Maybe<string> webkitMatchNearestMailBlockquoteColor;
    attribute Maybe<string> webkitMaxLogicalHeight;
    attribute Maybe<string> webkitMaxLogicalWidth;
    attribute Maybe<string> webkitMinLogicalHeight;
    attribute Maybe<string> webkitMinLogicalWidth;
    attribute Maybe<string> webkitNbspMode;
    attribute Maybe<string> webkitOverflowScrolling;
    attribute Maybe<string> webkitPaddingAfter;
    attribute Maybe<string> webkitPaddingBefore;
    attribute Maybe<string> webkitPaddingEnd;
    attribute Maybe<string> webkitPaddingStart;
    attribute Maybe<string> webkitPerspective;
    attribute Maybe<string> webkitPerspectiveOrigin;
    attribute Maybe<string> webkitPerspectiveOriginX;
    attribute Maybe<string> webkitPerspectiveOriginY;
    attribute Maybe<string> webkitPrintColorAdjust;
    attribute Maybe<string> webkitRegionBreakAfter;
    attribute Maybe<string> webkitRegionBreakBefore;
    attribute Maybe<string> webkitRegionBreakInside;
    attribute Maybe<string> webkitRegionOverflow;
    attribute Maybe<string> webkitRtlOrdering;
    attribute Maybe<string> webkitSvgShadow;
    attribute Maybe<string> webkitTapHighlightColor;
    attribute Maybe<string> webkitTextCombine;
    attribute Maybe<string> webkitTextDecorationsInEffect;
    attribute Maybe<string> webkitTextEmphasis;
    attribute Maybe<string> webkitTextEmphasisColor;
    attribute Maybe<string> webkitTextEmphasisPosition;
    attribute Maybe<string> webkitTextEmphasisStyle;
    attribute Maybe<string> webkitTextFillColor;
    attribute Maybe<string> webkitTextOrientation;
    attribute Maybe<string> webkitTextSecurity;
    attribute Maybe<string> webkitTextSizeAdjust;
    attribute Maybe<string> webkitTextStroke;
    attribute Maybe<string> webkitTextStrokeColor;
    attribute Maybe<string> webkitTextStrokeWidth;
    attribute Maybe<string> webkitTransform;
    attribute Maybe<string> webkitTransformOrigin;
    attribute Maybe<string> webkitTransformOriginX;
    attribute Maybe<string> webkitTransformOriginY;
    attribute Maybe<string> webkitTransformOriginZ;
    attribute Maybe<string> webkitTransformStyle;
    attribute Maybe<string> webkitTransition;
    attribute Maybe<string> webkitTransitionDelay;
    attribute Maybe<string> webkitTransitionDuration;
    attribute Maybe<string> webkitTransitionProperty;
    attribute Maybe<string> webkitTransitionTimingFunction;
    attribute Maybe<string> webkitUserDrag;
    attribute Maybe<string> webkitUserModify;
    attribute Maybe<string> webkitUserSelect;
    attribute Maybe<string> webkitWrap;
    attribute Maybe<string> webkitWrapFlow;
    attribute Maybe<string> webkitWrapMargin;
    attribute Maybe<string> webkitWrapPadding;
    attribute Maybe<string> webkitWrapShapeInside;
    attribute Maybe<string> webkitWrapShapeOutside;
    attribute Maybe<string> webkitWrapThrough;
    attribute Maybe<string> webkitWritingMode;
    attribute Maybe<string> whiteSpace;
    attribute Maybe<string> widows;
    attribute Maybe<string> width;
    attribute Maybe<string> wordBreak;
    attribute Maybe<string> wordSpacing;
    attribute Maybe<string> wordWrap;
    attribute Maybe<string> writingMode;
    attribute Maybe<string> zIndex;
    attribute Maybe<string> zoom;
};

