// http://html5labs.interoperabilitybridges.com/dom4events/

dictionary EventInit {

};

dictionary UIEventInit : EventInit {

};

dictionary MouseEventInit : UIEventInit {

};

dictionary ProgressEventInit : EventInit {
  boolean lengthComputable;
  unsigned long long loaded;
  unsigned long long total;
};

partial interface GlobalEventHandlers {
  attribute EventHandler oncontextmenu;
};

