// Firefox 12
//
// document.getElementById("input").innerHTML = (function(style) { var a = []; for(var k in style) { if(typeof style[k] === "function") continue; a.push("attribute Maybe<"+(typeof style[k])+"> "+k+";"+String.fromCharCode(0x0a)) }; return a.sort().join(""); }(document.body.style))

partial interface CSSStyleDeclaration {
    attribute Maybe<number> length;
    attribute Maybe<object> parentRule;
    attribute Maybe<string> MozAnimation;
    attribute Maybe<string> MozAnimationDelay;
    attribute Maybe<string> MozAnimationDirection;
    attribute Maybe<string> MozAnimationDuration;
    attribute Maybe<string> MozAnimationFillMode;
    attribute Maybe<string> MozAnimationIterationCount;
    attribute Maybe<string> MozAnimationName;
    attribute Maybe<string> MozAnimationPlayState;
    attribute Maybe<string> MozAnimationTimingFunction;
    attribute Maybe<string> MozAppearance;
    attribute Maybe<string> MozBackfaceVisibility;
    attribute Maybe<string> MozBackgroundInlinePolicy;
    attribute Maybe<string> MozBinding;
    attribute Maybe<string> MozBorderBottomColors;
    attribute Maybe<string> MozBorderEnd;
    attribute Maybe<string> MozBorderEndColor;
    attribute Maybe<string> MozBorderEndStyle;
    attribute Maybe<string> MozBorderEndWidth;
    attribute Maybe<string> MozBorderImage;
    attribute Maybe<string> MozBorderLeftColors;
    attribute Maybe<string> MozBorderRightColors;
    attribute Maybe<string> MozBorderStart;
    attribute Maybe<string> MozBorderStartColor;
    attribute Maybe<string> MozBorderStartStyle;
    attribute Maybe<string> MozBorderStartWidth;
    attribute Maybe<string> MozBorderTopColors;
    attribute Maybe<string> MozBoxAlign;
    attribute Maybe<string> MozBoxDirection;
    attribute Maybe<string> MozBoxFlex;
    attribute Maybe<string> MozBoxOrdinalGroup;
    attribute Maybe<string> MozBoxOrient;
    attribute Maybe<string> MozBoxPack;
    attribute Maybe<string> MozBoxSizing;
    attribute Maybe<string> MozColumnCount;
    attribute Maybe<string> MozColumnGap;
    attribute Maybe<string> MozColumnRule;
    attribute Maybe<string> MozColumnRuleColor;
    attribute Maybe<string> MozColumnRuleStyle;
    attribute Maybe<string> MozColumnRuleWidth;
    attribute Maybe<string> MozColumnWidth;
    attribute Maybe<string> MozColumns;
    attribute Maybe<string> MozFloatEdge;
    attribute Maybe<string> MozFontFeatureSettings;
    attribute Maybe<string> MozFontLanguageOverride;
    attribute Maybe<string> MozForceBrokenImageIcon;
    attribute Maybe<string> MozHyphens;
    attribute Maybe<string> MozImageRegion;
    attribute Maybe<string> MozMarginEnd;
    attribute Maybe<string> MozMarginStart;
    attribute Maybe<string> MozOpacity;
    attribute Maybe<string> MozOrient;
    attribute Maybe<string> MozOutline;
    attribute Maybe<string> MozOutlineColor;
    attribute Maybe<string> MozOutlineOffset;
    attribute Maybe<string> MozOutlineRadius;
    attribute Maybe<string> MozOutlineRadiusBottomleft;
    attribute Maybe<string> MozOutlineRadiusBottomright;
    attribute Maybe<string> MozOutlineRadiusTopleft;
    attribute Maybe<string> MozOutlineRadiusTopright;
    attribute Maybe<string> MozOutlineStyle;
    attribute Maybe<string> MozOutlineWidth;
    attribute Maybe<string> MozPaddingEnd;
    attribute Maybe<string> MozPaddingStart;
    attribute Maybe<string> MozPerspective;
    attribute Maybe<string> MozPerspectiveOrigin;
    attribute Maybe<string> MozStackSizing;
    attribute Maybe<string> MozTabSize;
    attribute Maybe<string> MozTextAlignLast;
    attribute Maybe<string> MozTextBlink;
    attribute Maybe<string> MozTextDecorationColor;
    attribute Maybe<string> MozTextDecorationLine;
    attribute Maybe<string> MozTextDecorationStyle;
    attribute Maybe<string> MozTextSizeAdjust;
    attribute Maybe<string> MozTransform;
    attribute Maybe<string> MozTransformOrigin;
    attribute Maybe<string> MozTransformStyle;
    attribute Maybe<string> MozTransition;
    attribute Maybe<string> MozTransitionDelay;
    attribute Maybe<string> MozTransitionDuration;
    attribute Maybe<string> MozTransitionProperty;
    attribute Maybe<string> MozTransitionTimingFunction;
    attribute Maybe<string> MozUserFocus;
    attribute Maybe<string> MozUserInput;
    attribute Maybe<string> MozUserModify;
    attribute Maybe<string> MozUserSelect;
    attribute Maybe<string> MozWindowShadow;
    attribute Maybe<string> background;
    attribute Maybe<string> backgroundAttachment;
    attribute Maybe<string> backgroundClip;
    attribute Maybe<string> backgroundColor;
    attribute Maybe<string> backgroundImage;
    attribute Maybe<string> backgroundOrigin;
    attribute Maybe<string> backgroundPosition;
    attribute Maybe<string> backgroundRepeat;
    attribute Maybe<string> backgroundSize;
    attribute Maybe<string> border;
    attribute Maybe<string> borderBottom;
    attribute Maybe<string> borderBottomColor;
    attribute Maybe<string> borderBottomLeftRadius;
    attribute Maybe<string> borderBottomRightRadius;
    attribute Maybe<string> borderBottomStyle;
    attribute Maybe<string> borderBottomWidth;
    attribute Maybe<string> borderCollapse;
    attribute Maybe<string> borderColor;
    attribute Maybe<string> borderLeft;
    attribute Maybe<string> borderLeftColor;
    attribute Maybe<string> borderLeftStyle;
    attribute Maybe<string> borderLeftWidth;
    attribute Maybe<string> borderRadius;
    attribute Maybe<string> borderRight;
    attribute Maybe<string> borderRightColor;
    attribute Maybe<string> borderRightStyle;
    attribute Maybe<string> borderRightWidth;
    attribute Maybe<string> borderSpacing;
    attribute Maybe<string> borderStyle;
    attribute Maybe<string> borderTop;
    attribute Maybe<string> borderTopColor;
    attribute Maybe<string> borderTopLeftRadius;
    attribute Maybe<string> borderTopRightRadius;
    attribute Maybe<string> borderTopStyle;
    attribute Maybe<string> borderTopWidth;
    attribute Maybe<string> borderWidth;
    attribute Maybe<string> bottom;
    attribute Maybe<string> boxShadow;
    attribute Maybe<string> captionSide;
    attribute Maybe<string> clear;
    attribute Maybe<string> clip;
    attribute Maybe<string> clipPath;
    attribute Maybe<string> clipRule;
    attribute Maybe<string> color;
    attribute Maybe<string> colorInterpolation;
    attribute Maybe<string> colorInterpolationFilters;
    attribute Maybe<string> content;
    attribute Maybe<string> counterIncrement;
    attribute Maybe<string> counterReset;
    attribute Maybe<string> cssFloat;
    attribute Maybe<string> cssText;
    attribute Maybe<string> cursor;
    attribute Maybe<string> direction;
    attribute Maybe<string> display;
    attribute Maybe<string> dominantBaseline;
    attribute Maybe<string> emptyCells;
    attribute Maybe<string> fill;
    attribute Maybe<string> fillOpacity;
    attribute Maybe<string> fillRule;
    attribute Maybe<string> filter;
    attribute Maybe<string> floodColor;
    attribute Maybe<string> floodOpacity;
    attribute Maybe<string> font;
    attribute Maybe<string> fontFamily;
    attribute Maybe<string> fontSize;
    attribute Maybe<string> fontSizeAdjust;
    attribute Maybe<string> fontStretch;
    attribute Maybe<string> fontStyle;
    attribute Maybe<string> fontVariant;
    attribute Maybe<string> fontWeight;
    attribute Maybe<string> height;
    attribute Maybe<string> imageRendering;
    attribute Maybe<string> imeMode;
    attribute Maybe<string> left;
    attribute Maybe<string> letterSpacing;
    attribute Maybe<string> lightingColor;
    attribute Maybe<string> lineHeight;
    attribute Maybe<string> listStyle;
    attribute Maybe<string> listStyleImage;
    attribute Maybe<string> listStylePosition;
    attribute Maybe<string> listStyleType;
    attribute Maybe<string> margin;
    attribute Maybe<string> marginBottom;
    attribute Maybe<string> marginLeft;
    attribute Maybe<string> marginRight;
    attribute Maybe<string> marginTop;
    attribute Maybe<string> marker;
    attribute Maybe<string> markerEnd;
    attribute Maybe<string> markerMid;
    attribute Maybe<string> markerOffset;
    attribute Maybe<string> markerStart;
    attribute Maybe<string> marks;
    attribute Maybe<string> mask;
    attribute Maybe<string> maxHeight;
    attribute Maybe<string> maxWidth;
    attribute Maybe<string> minHeight;
    attribute Maybe<string> minWidth;
    attribute Maybe<string> opacity;
    attribute Maybe<string> orphans;
    attribute Maybe<string> outline;
    attribute Maybe<string> outlineColor;
    attribute Maybe<string> outlineOffset;
    attribute Maybe<string> outlineStyle;
    attribute Maybe<string> outlineWidth;
    attribute Maybe<string> overflow;
    attribute Maybe<string> overflowX;
    attribute Maybe<string> overflowY;
    attribute Maybe<string> padding;
    attribute Maybe<string> paddingBottom;
    attribute Maybe<string> paddingLeft;
    attribute Maybe<string> paddingRight;
    attribute Maybe<string> paddingTop;
    attribute Maybe<string> page;
    attribute Maybe<string> pageBreakAfter;
    attribute Maybe<string> pageBreakBefore;
    attribute Maybe<string> pageBreakInside;
    attribute Maybe<string> pointerEvents;
    attribute Maybe<string> position;
    attribute Maybe<string> quotes;
    attribute Maybe<string> resize;
    attribute Maybe<string> right;
    attribute Maybe<string> shapeRendering;
    attribute Maybe<string> size;
    attribute Maybe<string> stopColor;
    attribute Maybe<string> stopOpacity;
    attribute Maybe<string> stroke;
    attribute Maybe<string> strokeDasharray;
    attribute Maybe<string> strokeDashoffset;
    attribute Maybe<string> strokeLinecap;
    attribute Maybe<string> strokeLinejoin;
    attribute Maybe<string> strokeMiterlimit;
    attribute Maybe<string> strokeOpacity;
    attribute Maybe<string> strokeWidth;
    attribute Maybe<string> tableLayout;
    attribute Maybe<string> textAlign;
    attribute Maybe<string> textAnchor;
    attribute Maybe<string> textDecoration;
    attribute Maybe<string> textIndent;
    attribute Maybe<string> textOverflow;
    attribute Maybe<string> textRendering;
    attribute Maybe<string> textShadow;
    attribute Maybe<string> textTransform;
    attribute Maybe<string> top;
    attribute Maybe<string> unicodeBidi;
    attribute Maybe<string> verticalAlign;
    attribute Maybe<string> visibility;
    attribute Maybe<string> whiteSpace;
    attribute Maybe<string> widows;
    attribute Maybe<string> width;
    attribute Maybe<string> wordSpacing;
    attribute Maybe<string> wordWrap;
    attribute Maybe<string> zIndex;
};
