// Firefox 17
//
// document.getElementById("input").innerHTML = (function(style) { var a = []; for(var k in style) { if(typeof style[k] === "function") continue; a.push("attribute "+(typeof style[k])+"? "+k+";"+String.fromCharCode(0x0a)) }; return a.sort().join(""); }(document.body.style))

partial interface CSSStyleDeclaration {
    attribute number? length;
    attribute object? parentRule;
    attribute string? MozAnimation;
    attribute string? MozAnimationDelay;
    attribute string? MozAnimationDirection;
    attribute string? MozAnimationDuration;
    attribute string? MozAnimationFillMode;
    attribute string? MozAnimationIterationCount;
    attribute string? MozAnimationName;
    attribute string? MozAnimationPlayState;
    attribute string? MozAnimationTimingFunction;
    attribute string? MozAppearance;
    attribute string? MozBackfaceVisibility;
    attribute string? MozBackgroundInlinePolicy;
    attribute string? MozBinding;
    attribute string? MozBorderBottomColors;
    attribute string? MozBorderEnd;
    attribute string? MozBorderEndColor;
    attribute string? MozBorderEndStyle;
    attribute string? MozBorderEndWidth;
    attribute string? MozBorderImage;
    attribute string? MozBorderLeftColors;
    attribute string? MozBorderRightColors;
    attribute string? MozBorderStart;
    attribute string? MozBorderStartColor;
    attribute string? MozBorderStartStyle;
    attribute string? MozBorderStartWidth;
    attribute string? MozBorderTopColors;
    attribute string? MozBoxAlign;
    attribute string? MozBoxDirection;
    attribute string? MozBoxFlex;
    attribute string? MozBoxOrdinalGroup;
    attribute string? MozBoxOrient;
    attribute string? MozBoxPack;
    attribute string? MozBoxSizing;
    attribute string? MozColumnCount;
    attribute string? MozColumnGap;
    attribute string? MozColumnRule;
    attribute string? MozColumnRuleColor;
    attribute string? MozColumnRuleStyle;
    attribute string? MozColumnRuleWidth;
    attribute string? MozColumnWidth;
    attribute string? MozColumns;
    attribute string? MozFloatEdge;
    attribute string? MozFontFeatureSettings;
    attribute string? MozFontLanguageOverride;
    attribute string? MozForceBrokenImageIcon;
    attribute string? MozHyphens;
    attribute string? MozImageRegion;
    attribute string? MozMarginEnd;
    attribute string? MozMarginStart;
    attribute string? MozOrient;
    attribute string? MozOutlineRadius;
    attribute string? MozOutlineRadiusBottomleft;
    attribute string? MozOutlineRadiusBottomright;
    attribute string? MozOutlineRadiusTopleft;
    attribute string? MozOutlineRadiusTopright;
    attribute string? MozPaddingEnd;
    attribute string? MozPaddingStart;
    attribute string? MozPerspective;
    attribute string? MozPerspectiveOrigin;
    attribute string? MozStackSizing;
    attribute string? MozTabSize;
    attribute string? MozTextAlignLast;
    attribute string? MozTextBlink;
    attribute string? MozTextDecorationColor;
    attribute string? MozTextDecorationLine;
    attribute string? MozTextDecorationStyle;
    attribute string? MozTextSizeAdjust;
    attribute string? MozTransform;
    attribute string? MozTransformOrigin;
    attribute string? MozTransformStyle;
    attribute string? MozTransition;
    attribute string? MozTransitionDelay;
    attribute string? MozTransitionDuration;
    attribute string? MozTransitionProperty;
    attribute string? MozTransitionTimingFunction;
    attribute string? MozUserFocus;
    attribute string? MozUserInput;
    attribute string? MozUserModify;
    attribute string? MozUserSelect;
    attribute string? MozWindowShadow;
    attribute string? animation;
    attribute string? animationDelay;
    attribute string? animationDirection;
    attribute string? animationDuration;
    attribute string? animationFillMode;
    attribute string? animationIterationCount;
    attribute string? animationName;
    attribute string? animationPlayState;
    attribute string? animationTimingFunction;
    attribute string? backfaceVisibility;
    attribute string? background;
    attribute string? backgroundAttachment;
    attribute string? backgroundClip;
    attribute string? backgroundColor;
    attribute string? backgroundImage;
    attribute string? backgroundOrigin;
    attribute string? backgroundPosition;
    attribute string? backgroundRepeat;
    attribute string? backgroundSize;
    attribute string? border;
    attribute string? borderBottom;
    attribute string? borderBottomColor;
    attribute string? borderBottomLeftRadius;
    attribute string? borderBottomRightRadius;
    attribute string? borderBottomStyle;
    attribute string? borderBottomWidth;
    attribute string? borderCollapse;
    attribute string? borderColor;
    attribute string? borderImage;
    attribute string? borderImageOutset;
    attribute string? borderImageRepeat;
    attribute string? borderImageSlice;
    attribute string? borderImageSource;
    attribute string? borderImageWidth;
    attribute string? borderLeft;
    attribute string? borderLeftColor;
    attribute string? borderLeftStyle;
    attribute string? borderLeftWidth;
    attribute string? borderRadius;
    attribute string? borderRight;
    attribute string? borderRightColor;
    attribute string? borderRightStyle;
    attribute string? borderRightWidth;
    attribute string? borderSpacing;
    attribute string? borderStyle;
    attribute string? borderTop;
    attribute string? borderTopColor;
    attribute string? borderTopLeftRadius;
    attribute string? borderTopRightRadius;
    attribute string? borderTopStyle;
    attribute string? borderTopWidth;
    attribute string? borderWidth;
    attribute string? bottom;
    attribute string? boxShadow;
    attribute string? captionSide;
    attribute string? clear;
    attribute string? clip;
    attribute string? clipPath;
    attribute string? clipRule;
    attribute string? color;
    attribute string? colorInterpolation;
    attribute string? colorInterpolationFilters;
    attribute string? content;
    attribute string? counterIncrement;
    attribute string? counterReset;
    attribute string? cssFloat;
    attribute string? cssText;
    attribute string? cursor;
    attribute string? direction;
    attribute string? display;
    attribute string? dominantBaseline;
    attribute string? emptyCells;
    attribute string? fill;
    attribute string? fillOpacity;
    attribute string? fillRule;
    attribute string? filter;
    attribute string? floodColor;
    attribute string? floodOpacity;
    attribute string? font;
    attribute string? fontFamily;
    attribute string? fontSize;
    attribute string? fontSizeAdjust;
    attribute string? fontStretch;
    attribute string? fontStyle;
    attribute string? fontVariant;
    attribute string? fontWeight;
    attribute string? height;
    attribute string? imageRendering;
    attribute string? imeMode;
    attribute string? left;
    attribute string? letterSpacing;
    attribute string? lightingColor;
    attribute string? lineHeight;
    attribute string? listStyle;
    attribute string? listStyleImage;
    attribute string? listStylePosition;
    attribute string? listStyleType;
    attribute string? margin;
    attribute string? marginBottom;
    attribute string? marginLeft;
    attribute string? marginRight;
    attribute string? marginTop;
    attribute string? marker;
    attribute string? markerEnd;
    attribute string? markerMid;
    attribute string? markerOffset;
    attribute string? markerStart;
    attribute string? marks;
    attribute string? mask;
    attribute string? maxHeight;
    attribute string? maxWidth;
    attribute string? minHeight;
    attribute string? minWidth;
    attribute string? opacity;
    attribute string? orphans;
    attribute string? outline;
    attribute string? outlineColor;
    attribute string? outlineOffset;
    attribute string? outlineStyle;
    attribute string? outlineWidth;
    attribute string? overflow;
    attribute string? overflowX;
    attribute string? overflowY;
    attribute string? padding;
    attribute string? paddingBottom;
    attribute string? paddingLeft;
    attribute string? paddingRight;
    attribute string? paddingTop;
    attribute string? page;
    attribute string? pageBreakAfter;
    attribute string? pageBreakBefore;
    attribute string? pageBreakInside;
    attribute string? perspective;
    attribute string? perspectiveOrigin;
    attribute string? pointerEvents;
    attribute string? position;
    attribute string? quotes;
    attribute string? resize;
    attribute string? right;
    attribute string? shapeRendering;
    attribute string? size;
    attribute string? stopColor;
    attribute string? stopOpacity;
    attribute string? stroke;
    attribute string? strokeDasharray;
    attribute string? strokeDashoffset;
    attribute string? strokeLinecap;
    attribute string? strokeLinejoin;
    attribute string? strokeMiterlimit;
    attribute string? strokeOpacity;
    attribute string? strokeWidth;
    attribute string? tableLayout;
    attribute string? textAlign;
    attribute string? textAnchor;
    attribute string? textDecoration;
    attribute string? textIndent;
    attribute string? textOverflow;
    attribute string? textRendering;
    attribute string? textShadow;
    attribute string? textTransform;
    attribute string? top;
    attribute string? transform;
    attribute string? transformOrigin;
    attribute string? transformStyle;
    attribute string? transition;
    attribute string? transitionDelay;
    attribute string? transitionDuration;
    attribute string? transitionProperty;
    attribute string? transitionTimingFunction;
    attribute string? unicodeBidi;
    attribute string? vectorEffect;
    attribute string? verticalAlign;
    attribute string? visibility;
    attribute string? whiteSpace;
    attribute string? widows;
    attribute string? width;
    attribute string? wordBreak;
    attribute string? wordSpacing;
    attribute string? wordWrap;
    attribute string? zIndex;
};
