// THIS FILE IS AUTOMATICALLY GENERATED.
/*

CSS Object Model View

Specification:
    http://dev.w3.org/csswg/cssom-view/
    http://www.w3.org/TR/cssom-view/
*/

import "./dom.jsx";

/*
automatically generated from:
	http://dev.w3.org/csswg/cssom/
	http://dev.w3.org/csswg/cssom-view/
	idl2jsx/extra/chrome.idl
	idl2jsx/extra/firefox.idl
*/
native class MediaList {

	var mediaText : string/*DOMString*/;
	__readonly__ var length : int/*unsigned long*/;
	function __native_index_operator__(
		index : int/*unsigned long*/
	) : MayBeUndefined.<string/*DOMString*/>;
	function /* getter */ item(
		index : int/*unsigned long*/
	) : MayBeUndefined.<string/*DOMString*/>;
	function appendMedium(medium : string/*DOMString*/) : void;
	function deleteMedium(medium : string/*DOMString*/) : void;

} // end of MediaList

native class StyleSheet {

	__readonly__ var type : string/*DOMString*/;
	__readonly__ var href : string/*DOMString*/;
	__readonly__ var ownerNode : Node;
	__readonly__ var parentStyleSheet : StyleSheet;
	__readonly__ var title : string/*DOMString*/;
	__readonly__ var media : MediaList;
	var disabled : boolean;

} // end of StyleSheet

native class CSSStyleSheet extends StyleSheet {

	__readonly__ var ownerRule : CSSRule;
	__readonly__ var cssRules : CSSRule[]/*CSSRuleList*/;
	function insertRule(
		rule : string/*DOMString*/,
		index : int/*unsigned long*/
	) : int/*unsigned long*/;
	function deleteRule(index : int/*unsigned long*/) : void;

} // end of CSSStyleSheet

native class CSSRule {

	// Types
	static const     STYLE_RULE : int/*unsigned short*/;
	__readonly__ var STYLE_RULE : int/*unsigned short*/;
	static const     IMPORT_RULE : int/*unsigned short*/;
	__readonly__ var IMPORT_RULE : int/*unsigned short*/;
	static const     MEDIA_RULE : int/*unsigned short*/;
	__readonly__ var MEDIA_RULE : int/*unsigned short*/;
	static const     FONT_FACE_RULE : int/*unsigned short*/;
	__readonly__ var FONT_FACE_RULE : int/*unsigned short*/;
	static const     PAGE_RULE : int/*unsigned short*/;
	__readonly__ var PAGE_RULE : int/*unsigned short*/;
	static const     NAMESPACE_RULE : int/*unsigned short*/;
	__readonly__ var NAMESPACE_RULE : int/*unsigned short*/;
	__readonly__ var type : int/*unsigned short*/;
	// Parsing and serialization
	var cssText : string/*DOMString*/;
	// Context
	__readonly__ var parentRule : CSSRule;
	__readonly__ var parentStyleSheet : CSSStyleSheet;

} // end of CSSRule

native class CSSStyleRule extends CSSRule {

	var selectorText : string/*DOMString*/;
	__readonly__ var style : CSSStyleDeclaration;

} // end of CSSStyleRule

native class CSSImportRule extends CSSRule {

	__readonly__ var href : string/*DOMString*/;
	__readonly__ var media : MediaList;
	__readonly__ var styleSheet : CSSStyleSheet;

} // end of CSSImportRule

native class CSSMediaRule extends CSSRule {

	__readonly__ var media : MediaList;
	__readonly__ var cssRules : CSSRule[]/*CSSRuleList*/;
	function insertRule(
		rule : string/*DOMString*/,
		index : int/*unsigned long*/
	) : int/*unsigned long*/;
	function deleteRule(index : int/*unsigned long*/) : void;

} // end of CSSMediaRule

native class CSSFontFaceRule extends CSSRule {

	__readonly__ var style : CSSStyleDeclaration;

} // end of CSSFontFaceRule

native class CSSPageRule extends CSSRule {

	var selectorText : string/*DOMString*/;
	__readonly__ var style : CSSStyleDeclaration;

} // end of CSSPageRule

native class CSSNamespaceRule extends CSSRule {

	__readonly__ var namespaceURI : string/*DOMString*/;
	__readonly__ var prefix : string/*DOMString?*/;

} // end of CSSNamespaceRule

native class CSSStyleDeclaration {

	var cssText : string/*DOMString*/;
	__readonly__ var length : int/*unsigned long*/;
	function item(index : int/*unsigned long*/) : string/*DOMString*/;
	function getPropertyValue(
		property : string/*DOMString*/
	) : string/*DOMString*/;
	function getPropertyPriority(
		property : string/*DOMString*/
	) : string/*DOMString*/;
	function setProperty(
		property : string/*DOMString*/,
		value : string/*DOMString*/
	) : void;
	function setProperty(
		property : string/*DOMString*/,
		value : string/*DOMString*/,
		priority : string/*DOMString*/
	) : void;
	function removeProperty(
		property : string/*DOMString*/
	) : string/*DOMString*/;
	__readonly__ var parentRule : CSSRule;
	// CSS Properties
	var azimuth : string/*DOMString*/;
	var background : string/*DOMString*/;
	var backgroundAttachment : string/*DOMString*/;
	var backgroundColor : string/*DOMString*/;
	var backgroundImage : string/*DOMString*/;
	var backgroundPosition : string/*DOMString*/;
	var backgroundRepeat : string/*DOMString*/;
	var border : string/*DOMString*/;
	var borderCollapse : string/*DOMString*/;
	var borderColor : string/*DOMString*/;
	var borderSpacing : string/*DOMString*/;
	var borderStyle : string/*DOMString*/;
	var borderTop : string/*DOMString*/;
	var borderRight : string/*DOMString*/;
	var borderBottom : string/*DOMString*/;
	var borderLeft : string/*DOMString*/;
	var borderTopColor : string/*DOMString*/;
	var borderRightColor : string/*DOMString*/;
	var borderBottomColor : string/*DOMString*/;
	var borderLeftColor : string/*DOMString*/;
	var borderTopStyle : string/*DOMString*/;
	var borderRightStyle : string/*DOMString*/;
	var borderBottomStyle : string/*DOMString*/;
	var borderLeftStyle : string/*DOMString*/;
	var borderTopWidth : string/*DOMString*/;
	var borderRightWidth : string/*DOMString*/;
	var borderBottomWidth : string/*DOMString*/;
	var borderLeftWidth : string/*DOMString*/;
	var borderWidth : string/*DOMString*/;
	var bottom : string/*DOMString*/;
	var captionSide : string/*DOMString*/;
	var clear : string/*DOMString*/;
	var clip : string/*DOMString*/;
	var color : string/*DOMString*/;
	var content : string/*DOMString*/;
	var counterIncrement : string/*DOMString*/;
	var counterReset : string/*DOMString*/;
	var cue : string/*DOMString*/;
	var cueAfter : string/*DOMString*/;
	var cueBefore : string/*DOMString*/;
	var cursor : string/*DOMString*/;
	var direction : string/*DOMString*/;
	var display : string/*DOMString*/;
	var elevation : string/*DOMString*/;
	var emptyCells : string/*DOMString*/;
	var cssFloat : string/*DOMString*/;
	var font : string/*DOMString*/;
	var fontFamily : string/*DOMString*/;
	var fontSize : string/*DOMString*/;
	var fontSizeAdjust : string/*DOMString*/;
	var fontStretch : string/*DOMString*/;
	var fontStyle : string/*DOMString*/;
	var fontVariant : string/*DOMString*/;
	var fontWeight : string/*DOMString*/;
	var height : string/*DOMString*/;
	var left : string/*DOMString*/;
	var letterSpacing : string/*DOMString*/;
	var lineHeight : string/*DOMString*/;
	var listStyle : string/*DOMString*/;
	var listStyleImage : string/*DOMString*/;
	var listStylePosition : string/*DOMString*/;
	var listStyleType : string/*DOMString*/;
	var margin : string/*DOMString*/;
	var marginTop : string/*DOMString*/;
	var marginRight : string/*DOMString*/;
	var marginBottom : string/*DOMString*/;
	var marginLeft : string/*DOMString*/;
	var markerOffset : string/*DOMString*/;
	var marks : string/*DOMString*/;
	var maxHeight : string/*DOMString*/;
	var maxWidth : string/*DOMString*/;
	var minHeight : string/*DOMString*/;
	var minWidth : string/*DOMString*/;
	var orphans : string/*DOMString*/;
	var outline : string/*DOMString*/;
	var outlineColor : string/*DOMString*/;
	var outlineStyle : string/*DOMString*/;
	var outlineWidth : string/*DOMString*/;
	var overflow : string/*DOMString*/;
	var padding : string/*DOMString*/;
	var paddingTop : string/*DOMString*/;
	var paddingRight : string/*DOMString*/;
	var paddingBottom : string/*DOMString*/;
	var paddingLeft : string/*DOMString*/;
	var page : string/*DOMString*/;
	var pageBreakAfter : string/*DOMString*/;
	var pageBreakBefore : string/*DOMString*/;
	var pageBreakInside : string/*DOMString*/;
	var pause : string/*DOMString*/;
	var pauseAfter : string/*DOMString*/;
	var pauseBefore : string/*DOMString*/;
	var pitch : string/*DOMString*/;
	var pitchRange : string/*DOMString*/;
	var playDuring : string/*DOMString*/;
	var position : string/*DOMString*/;
	var quotes : string/*DOMString*/;
	var richness : string/*DOMString*/;
	var right : string/*DOMString*/;
	var size : string/*DOMString*/;
	var speak : string/*DOMString*/;
	var speakHeader : string/*DOMString*/;
	var speakNumeral : string/*DOMString*/;
	var speakPunctuation : string/*DOMString*/;
	var speechRate : string/*DOMString*/;
	var stress : string/*DOMString*/;
	var tableLayout : string/*DOMString*/;
	var textAlign : string/*DOMString*/;
	var textDecoration : string/*DOMString*/;
	var textIndent : string/*DOMString*/;
	var textShadow : string/*DOMString*/;
	var textTransform : string/*DOMString*/;
	var top : string/*DOMString*/;
	var unicodeBidi : string/*DOMString*/;
	var verticalAlign : string/*DOMString*/;
	var visibility : string/*DOMString*/;
	var voiceFamily : string/*DOMString*/;
	var volume : string/*DOMString*/;
	var whiteSpace : string/*DOMString*/;
	var widows : string/*DOMString*/;
	var width : string/*DOMString*/;
	var wordSpacing : string/*DOMString*/;
	var zIndex : string/*DOMString*/;

	var alignmentBaseline : MayBeUndefined.<string>;
	var backgroundClip : MayBeUndefined.<string>;
	var backgroundOrigin : MayBeUndefined.<string>;
	var backgroundPositionX : MayBeUndefined.<string>;
	var backgroundPositionY : MayBeUndefined.<string>;
	var backgroundRepeatX : MayBeUndefined.<string>;
	var backgroundRepeatY : MayBeUndefined.<string>;
	var backgroundSize : MayBeUndefined.<string>;
	var baselineShift : MayBeUndefined.<string>;
	var borderBottomLeftRadius : MayBeUndefined.<string>;
	var borderBottomRightRadius : MayBeUndefined.<string>;
	var borderImage : MayBeUndefined.<string>;
	var borderImageOutset : MayBeUndefined.<string>;
	var borderImageRepeat : MayBeUndefined.<string>;
	var borderImageSlice : MayBeUndefined.<string>;
	var borderImageSource : MayBeUndefined.<string>;
	var borderImageWidth : MayBeUndefined.<string>;
	var borderRadius : MayBeUndefined.<string>;
	var borderTopLeftRadius : MayBeUndefined.<string>;
	var borderTopRightRadius : MayBeUndefined.<string>;
	var boxShadow : MayBeUndefined.<string>;
	var boxSizing : MayBeUndefined.<string>;
	var clipPath : MayBeUndefined.<string>;
	var clipRule : MayBeUndefined.<string>;
	var colorInterpolation : MayBeUndefined.<string>;
	var colorInterpolationFilters : MayBeUndefined.<string>;
	var colorProfile : MayBeUndefined.<string>;
	var colorRendering : MayBeUndefined.<string>;
	var dominantBaseline : MayBeUndefined.<string>;
	var enableBackground : MayBeUndefined.<string>;
	var fill : MayBeUndefined.<string>;
	var fillOpacity : MayBeUndefined.<string>;
	var fillRule : MayBeUndefined.<string>;
	var filter : MayBeUndefined.<string>;
	var float : MayBeUndefined.<string>;
	var floodColor : MayBeUndefined.<string>;
	var floodOpacity : MayBeUndefined.<string>;
	var glyphOrientationHorizontal : MayBeUndefined.<string>;
	var glyphOrientationVertical : MayBeUndefined.<string>;
	var imageRendering : MayBeUndefined.<string>;
	var kerning : MayBeUndefined.<string>;
	var lightingColor : MayBeUndefined.<string>;
	var marker : MayBeUndefined.<string>;
	var markerEnd : MayBeUndefined.<string>;
	var markerMid : MayBeUndefined.<string>;
	var markerStart : MayBeUndefined.<string>;
	var mask : MayBeUndefined.<string>;
	var opacity : MayBeUndefined.<string>;
	var outlineOffset : MayBeUndefined.<string>;
	var overflowX : MayBeUndefined.<string>;
	var overflowY : MayBeUndefined.<string>;
	var pointerEvents : MayBeUndefined.<string>;
	var resize : MayBeUndefined.<string>;
	var shapeRendering : MayBeUndefined.<string>;
	var src : MayBeUndefined.<string>;
	var stopColor : MayBeUndefined.<string>;
	var stopOpacity : MayBeUndefined.<string>;
	var stroke : MayBeUndefined.<string>;
	var strokeDasharray : MayBeUndefined.<string>;
	var strokeDashoffset : MayBeUndefined.<string>;
	var strokeLinecap : MayBeUndefined.<string>;
	var strokeLinejoin : MayBeUndefined.<string>;
	var strokeMiterlimit : MayBeUndefined.<string>;
	var strokeOpacity : MayBeUndefined.<string>;
	var strokeWidth : MayBeUndefined.<string>;
	var textAnchor : MayBeUndefined.<string>;
	var textLineThrough : MayBeUndefined.<string>;
	var textLineThroughColor : MayBeUndefined.<string>;
	var textLineThroughMode : MayBeUndefined.<string>;
	var textLineThroughStyle : MayBeUndefined.<string>;
	var textLineThroughWidth : MayBeUndefined.<string>;
	var textOverflow : MayBeUndefined.<string>;
	var textOverline : MayBeUndefined.<string>;
	var textOverlineColor : MayBeUndefined.<string>;
	var textOverlineMode : MayBeUndefined.<string>;
	var textOverlineStyle : MayBeUndefined.<string>;
	var textOverlineWidth : MayBeUndefined.<string>;
	var textRendering : MayBeUndefined.<string>;
	var textUnderline : MayBeUndefined.<string>;
	var textUnderlineColor : MayBeUndefined.<string>;
	var textUnderlineMode : MayBeUndefined.<string>;
	var textUnderlineStyle : MayBeUndefined.<string>;
	var textUnderlineWidth : MayBeUndefined.<string>;
	var unicodeRange : MayBeUndefined.<string>;
	var vectorEffect : MayBeUndefined.<string>;
	var webkitAnimation : MayBeUndefined.<string>;
	var webkitAnimationDelay : MayBeUndefined.<string>;
	var webkitAnimationDirection : MayBeUndefined.<string>;
	var webkitAnimationDuration : MayBeUndefined.<string>;
	var webkitAnimationFillMode : MayBeUndefined.<string>;
	var webkitAnimationIterationCount : MayBeUndefined.<string>;
	var webkitAnimationName : MayBeUndefined.<string>;
	var webkitAnimationPlayState : MayBeUndefined.<string>;
	var webkitAnimationTimingFunction : MayBeUndefined.<string>;
	var webkitAppearance : MayBeUndefined.<string>;
	var webkitAspectRatio : MayBeUndefined.<string>;
	var webkitBackfaceVisibility : MayBeUndefined.<string>;
	var webkitBackgroundClip : MayBeUndefined.<string>;
	var webkitBackgroundComposite : MayBeUndefined.<string>;
	var webkitBackgroundOrigin : MayBeUndefined.<string>;
	var webkitBackgroundSize : MayBeUndefined.<string>;
	var webkitBorderAfter : MayBeUndefined.<string>;
	var webkitBorderAfterColor : MayBeUndefined.<string>;
	var webkitBorderAfterStyle : MayBeUndefined.<string>;
	var webkitBorderAfterWidth : MayBeUndefined.<string>;
	var webkitBorderBefore : MayBeUndefined.<string>;
	var webkitBorderBeforeColor : MayBeUndefined.<string>;
	var webkitBorderBeforeStyle : MayBeUndefined.<string>;
	var webkitBorderBeforeWidth : MayBeUndefined.<string>;
	var webkitBorderEnd : MayBeUndefined.<string>;
	var webkitBorderEndColor : MayBeUndefined.<string>;
	var webkitBorderEndStyle : MayBeUndefined.<string>;
	var webkitBorderEndWidth : MayBeUndefined.<string>;
	var webkitBorderFit : MayBeUndefined.<string>;
	var webkitBorderHorizontalSpacing : MayBeUndefined.<string>;
	var webkitBorderImage : MayBeUndefined.<string>;
	var webkitBorderRadius : MayBeUndefined.<string>;
	var webkitBorderStart : MayBeUndefined.<string>;
	var webkitBorderStartColor : MayBeUndefined.<string>;
	var webkitBorderStartStyle : MayBeUndefined.<string>;
	var webkitBorderStartWidth : MayBeUndefined.<string>;
	var webkitBorderVerticalSpacing : MayBeUndefined.<string>;
	var webkitBoxAlign : MayBeUndefined.<string>;
	var webkitBoxDirection : MayBeUndefined.<string>;
	var webkitBoxFlex : MayBeUndefined.<string>;
	var webkitBoxFlexGroup : MayBeUndefined.<string>;
	var webkitBoxLines : MayBeUndefined.<string>;
	var webkitBoxOrdinalGroup : MayBeUndefined.<string>;
	var webkitBoxOrient : MayBeUndefined.<string>;
	var webkitBoxPack : MayBeUndefined.<string>;
	var webkitBoxReflect : MayBeUndefined.<string>;
	var webkitBoxShadow : MayBeUndefined.<string>;
	var webkitColorCorrection : MayBeUndefined.<string>;
	var webkitColumnAxis : MayBeUndefined.<string>;
	var webkitColumnBreakAfter : MayBeUndefined.<string>;
	var webkitColumnBreakBefore : MayBeUndefined.<string>;
	var webkitColumnBreakInside : MayBeUndefined.<string>;
	var webkitColumnCount : MayBeUndefined.<string>;
	var webkitColumnGap : MayBeUndefined.<string>;
	var webkitColumnRule : MayBeUndefined.<string>;
	var webkitColumnRuleColor : MayBeUndefined.<string>;
	var webkitColumnRuleStyle : MayBeUndefined.<string>;
	var webkitColumnRuleWidth : MayBeUndefined.<string>;
	var webkitColumnSpan : MayBeUndefined.<string>;
	var webkitColumnWidth : MayBeUndefined.<string>;
	var webkitColumns : MayBeUndefined.<string>;
	var webkitFilter : MayBeUndefined.<string>;
	var webkitFlexAlign : MayBeUndefined.<string>;
	var webkitFlexDirection : MayBeUndefined.<string>;
	var webkitFlexFlow : MayBeUndefined.<string>;
	var webkitFlexItemAlign : MayBeUndefined.<string>;
	var webkitFlexLinePack : MayBeUndefined.<string>;
	var webkitFlexOrder : MayBeUndefined.<string>;
	var webkitFlexPack : MayBeUndefined.<string>;
	var webkitFlexWrap : MayBeUndefined.<string>;
	var webkitFlowFrom : MayBeUndefined.<string>;
	var webkitFlowInto : MayBeUndefined.<string>;
	var webkitFontFeatureSettings : MayBeUndefined.<string>;
	var webkitFontKerning : MayBeUndefined.<string>;
	var webkitFontSizeDelta : MayBeUndefined.<string>;
	var webkitFontSmoothing : MayBeUndefined.<string>;
	var webkitFontVariantLigatures : MayBeUndefined.<string>;
	var webkitHighlight : MayBeUndefined.<string>;
	var webkitHyphenateCharacter : MayBeUndefined.<string>;
	var webkitHyphenateLimitAfter : MayBeUndefined.<string>;
	var webkitHyphenateLimitBefore : MayBeUndefined.<string>;
	var webkitHyphenateLimitLines : MayBeUndefined.<string>;
	var webkitHyphens : MayBeUndefined.<string>;
	var webkitLineAlign : MayBeUndefined.<string>;
	var webkitLineBoxContain : MayBeUndefined.<string>;
	var webkitLineBreak : MayBeUndefined.<string>;
	var webkitLineClamp : MayBeUndefined.<string>;
	var webkitLineGrid : MayBeUndefined.<string>;
	var webkitLineSnap : MayBeUndefined.<string>;
	var webkitLocale : MayBeUndefined.<string>;
	var webkitLogicalHeight : MayBeUndefined.<string>;
	var webkitLogicalWidth : MayBeUndefined.<string>;
	var webkitMarginAfter : MayBeUndefined.<string>;
	var webkitMarginAfterCollapse : MayBeUndefined.<string>;
	var webkitMarginBefore : MayBeUndefined.<string>;
	var webkitMarginBeforeCollapse : MayBeUndefined.<string>;
	var webkitMarginBottomCollapse : MayBeUndefined.<string>;
	var webkitMarginCollapse : MayBeUndefined.<string>;
	var webkitMarginEnd : MayBeUndefined.<string>;
	var webkitMarginStart : MayBeUndefined.<string>;
	var webkitMarginTopCollapse : MayBeUndefined.<string>;
	var webkitMarquee : MayBeUndefined.<string>;
	var webkitMarqueeDirection : MayBeUndefined.<string>;
	var webkitMarqueeIncrement : MayBeUndefined.<string>;
	var webkitMarqueeRepetition : MayBeUndefined.<string>;
	var webkitMarqueeSpeed : MayBeUndefined.<string>;
	var webkitMarqueeStyle : MayBeUndefined.<string>;
	var webkitMask : MayBeUndefined.<string>;
	var webkitMaskAttachment : MayBeUndefined.<string>;
	var webkitMaskBoxImage : MayBeUndefined.<string>;
	var webkitMaskBoxImageOutset : MayBeUndefined.<string>;
	var webkitMaskBoxImageRepeat : MayBeUndefined.<string>;
	var webkitMaskBoxImageSlice : MayBeUndefined.<string>;
	var webkitMaskBoxImageSource : MayBeUndefined.<string>;
	var webkitMaskBoxImageWidth : MayBeUndefined.<string>;
	var webkitMaskClip : MayBeUndefined.<string>;
	var webkitMaskComposite : MayBeUndefined.<string>;
	var webkitMaskImage : MayBeUndefined.<string>;
	var webkitMaskOrigin : MayBeUndefined.<string>;
	var webkitMaskPosition : MayBeUndefined.<string>;
	var webkitMaskPositionX : MayBeUndefined.<string>;
	var webkitMaskPositionY : MayBeUndefined.<string>;
	var webkitMaskRepeat : MayBeUndefined.<string>;
	var webkitMaskRepeatX : MayBeUndefined.<string>;
	var webkitMaskRepeatY : MayBeUndefined.<string>;
	var webkitMaskSize : MayBeUndefined.<string>;
	var webkitMatchNearestMailBlockquoteColor : MayBeUndefined.<string>;
	var webkitMaxLogicalHeight : MayBeUndefined.<string>;
	var webkitMaxLogicalWidth : MayBeUndefined.<string>;
	var webkitMinLogicalHeight : MayBeUndefined.<string>;
	var webkitMinLogicalWidth : MayBeUndefined.<string>;
	var webkitNbspMode : MayBeUndefined.<string>;
	var webkitOverflowScrolling : MayBeUndefined.<string>;
	var webkitPaddingAfter : MayBeUndefined.<string>;
	var webkitPaddingBefore : MayBeUndefined.<string>;
	var webkitPaddingEnd : MayBeUndefined.<string>;
	var webkitPaddingStart : MayBeUndefined.<string>;
	var webkitPerspective : MayBeUndefined.<string>;
	var webkitPerspectiveOrigin : MayBeUndefined.<string>;
	var webkitPerspectiveOriginX : MayBeUndefined.<string>;
	var webkitPerspectiveOriginY : MayBeUndefined.<string>;
	var webkitPrintColorAdjust : MayBeUndefined.<string>;
	var webkitRegionBreakAfter : MayBeUndefined.<string>;
	var webkitRegionBreakBefore : MayBeUndefined.<string>;
	var webkitRegionBreakInside : MayBeUndefined.<string>;
	var webkitRegionOverflow : MayBeUndefined.<string>;
	var webkitRtlOrdering : MayBeUndefined.<string>;
	var webkitSvgShadow : MayBeUndefined.<string>;
	var webkitTapHighlightColor : MayBeUndefined.<string>;
	var webkitTextCombine : MayBeUndefined.<string>;
	var webkitTextDecorationsInEffect : MayBeUndefined.<string>;
	var webkitTextEmphasis : MayBeUndefined.<string>;
	var webkitTextEmphasisColor : MayBeUndefined.<string>;
	var webkitTextEmphasisPosition : MayBeUndefined.<string>;
	var webkitTextEmphasisStyle : MayBeUndefined.<string>;
	var webkitTextFillColor : MayBeUndefined.<string>;
	var webkitTextOrientation : MayBeUndefined.<string>;
	var webkitTextSecurity : MayBeUndefined.<string>;
	var webkitTextSizeAdjust : MayBeUndefined.<string>;
	var webkitTextStroke : MayBeUndefined.<string>;
	var webkitTextStrokeColor : MayBeUndefined.<string>;
	var webkitTextStrokeWidth : MayBeUndefined.<string>;
	var webkitTransform : MayBeUndefined.<string>;
	var webkitTransformOrigin : MayBeUndefined.<string>;
	var webkitTransformOriginX : MayBeUndefined.<string>;
	var webkitTransformOriginY : MayBeUndefined.<string>;
	var webkitTransformOriginZ : MayBeUndefined.<string>;
	var webkitTransformStyle : MayBeUndefined.<string>;
	var webkitTransition : MayBeUndefined.<string>;
	var webkitTransitionDelay : MayBeUndefined.<string>;
	var webkitTransitionDuration : MayBeUndefined.<string>;
	var webkitTransitionProperty : MayBeUndefined.<string>;
	var webkitTransitionTimingFunction : MayBeUndefined.<string>;
	var webkitUserDrag : MayBeUndefined.<string>;
	var webkitUserModify : MayBeUndefined.<string>;
	var webkitUserSelect : MayBeUndefined.<string>;
	var webkitWrap : MayBeUndefined.<string>;
	var webkitWrapFlow : MayBeUndefined.<string>;
	var webkitWrapMargin : MayBeUndefined.<string>;
	var webkitWrapPadding : MayBeUndefined.<string>;
	var webkitWrapShapeInside : MayBeUndefined.<string>;
	var webkitWrapShapeOutside : MayBeUndefined.<string>;
	var webkitWrapThrough : MayBeUndefined.<string>;
	var webkitWritingMode : MayBeUndefined.<string>;
	var wordBreak : MayBeUndefined.<string>;
	var wordWrap : MayBeUndefined.<string>;
	var writingMode : MayBeUndefined.<string>;
	var zoom : MayBeUndefined.<string>;

	var MozAnimation : MayBeUndefined.<string>;
	var MozAnimationDelay : MayBeUndefined.<string>;
	var MozAnimationDirection : MayBeUndefined.<string>;
	var MozAnimationDuration : MayBeUndefined.<string>;
	var MozAnimationFillMode : MayBeUndefined.<string>;
	var MozAnimationIterationCount : MayBeUndefined.<string>;
	var MozAnimationName : MayBeUndefined.<string>;
	var MozAnimationPlayState : MayBeUndefined.<string>;
	var MozAnimationTimingFunction : MayBeUndefined.<string>;
	var MozAppearance : MayBeUndefined.<string>;
	var MozBackfaceVisibility : MayBeUndefined.<string>;
	var MozBackgroundInlinePolicy : MayBeUndefined.<string>;
	var MozBinding : MayBeUndefined.<string>;
	var MozBorderBottomColors : MayBeUndefined.<string>;
	var MozBorderEnd : MayBeUndefined.<string>;
	var MozBorderEndColor : MayBeUndefined.<string>;
	var MozBorderEndStyle : MayBeUndefined.<string>;
	var MozBorderEndWidth : MayBeUndefined.<string>;
	var MozBorderImage : MayBeUndefined.<string>;
	var MozBorderLeftColors : MayBeUndefined.<string>;
	var MozBorderRightColors : MayBeUndefined.<string>;
	var MozBorderStart : MayBeUndefined.<string>;
	var MozBorderStartColor : MayBeUndefined.<string>;
	var MozBorderStartStyle : MayBeUndefined.<string>;
	var MozBorderStartWidth : MayBeUndefined.<string>;
	var MozBorderTopColors : MayBeUndefined.<string>;
	var MozBoxAlign : MayBeUndefined.<string>;
	var MozBoxDirection : MayBeUndefined.<string>;
	var MozBoxFlex : MayBeUndefined.<string>;
	var MozBoxOrdinalGroup : MayBeUndefined.<string>;
	var MozBoxOrient : MayBeUndefined.<string>;
	var MozBoxPack : MayBeUndefined.<string>;
	var MozBoxSizing : MayBeUndefined.<string>;
	var MozColumnCount : MayBeUndefined.<string>;
	var MozColumnGap : MayBeUndefined.<string>;
	var MozColumnRule : MayBeUndefined.<string>;
	var MozColumnRuleColor : MayBeUndefined.<string>;
	var MozColumnRuleStyle : MayBeUndefined.<string>;
	var MozColumnRuleWidth : MayBeUndefined.<string>;
	var MozColumnWidth : MayBeUndefined.<string>;
	var MozColumns : MayBeUndefined.<string>;
	var MozFloatEdge : MayBeUndefined.<string>;
	var MozFontFeatureSettings : MayBeUndefined.<string>;
	var MozFontLanguageOverride : MayBeUndefined.<string>;
	var MozForceBrokenImageIcon : MayBeUndefined.<string>;
	var MozHyphens : MayBeUndefined.<string>;
	var MozImageRegion : MayBeUndefined.<string>;
	var MozMarginEnd : MayBeUndefined.<string>;
	var MozMarginStart : MayBeUndefined.<string>;
	var MozOpacity : MayBeUndefined.<string>;
	var MozOrient : MayBeUndefined.<string>;
	var MozOutline : MayBeUndefined.<string>;
	var MozOutlineColor : MayBeUndefined.<string>;
	var MozOutlineOffset : MayBeUndefined.<string>;
	var MozOutlineRadius : MayBeUndefined.<string>;
	var MozOutlineRadiusBottomleft : MayBeUndefined.<string>;
	var MozOutlineRadiusBottomright : MayBeUndefined.<string>;
	var MozOutlineRadiusTopleft : MayBeUndefined.<string>;
	var MozOutlineRadiusTopright : MayBeUndefined.<string>;
	var MozOutlineStyle : MayBeUndefined.<string>;
	var MozOutlineWidth : MayBeUndefined.<string>;
	var MozPaddingEnd : MayBeUndefined.<string>;
	var MozPaddingStart : MayBeUndefined.<string>;
	var MozPerspective : MayBeUndefined.<string>;
	var MozPerspectiveOrigin : MayBeUndefined.<string>;
	var MozStackSizing : MayBeUndefined.<string>;
	var MozTabSize : MayBeUndefined.<string>;
	var MozTextAlignLast : MayBeUndefined.<string>;
	var MozTextBlink : MayBeUndefined.<string>;
	var MozTextDecorationColor : MayBeUndefined.<string>;
	var MozTextDecorationLine : MayBeUndefined.<string>;
	var MozTextDecorationStyle : MayBeUndefined.<string>;
	var MozTextSizeAdjust : MayBeUndefined.<string>;
	var MozTransform : MayBeUndefined.<string>;
	var MozTransformOrigin : MayBeUndefined.<string>;
	var MozTransformStyle : MayBeUndefined.<string>;
	var MozTransition : MayBeUndefined.<string>;
	var MozTransitionDelay : MayBeUndefined.<string>;
	var MozTransitionDuration : MayBeUndefined.<string>;
	var MozTransitionProperty : MayBeUndefined.<string>;
	var MozTransitionTimingFunction : MayBeUndefined.<string>;
	var MozUserFocus : MayBeUndefined.<string>;
	var MozUserInput : MayBeUndefined.<string>;
	var MozUserModify : MayBeUndefined.<string>;
	var MozUserSelect : MayBeUndefined.<string>;
	var MozWindowShadow : MayBeUndefined.<string>;
	var imeMode : MayBeUndefined.<string>;

} // end of CSSStyleDeclaration

native class ElementCSSInlineStyle {

	__readonly__ var style : CSSStyleDeclaration;

} // end of ElementCSSInlineStyle

native class MediaQueryList {

	__readonly__ var media : string/*DOMString*/;
	__readonly__ var matches : boolean;
	function addListener(
		listener : function(:MediaQueryList):void/*MediaQueryListListener*/
	) : void;
	function removeListener(
		listener : function(:MediaQueryList):void/*MediaQueryListListener*/
	) : void;

} // end of MediaQueryList

native class MediaQueryListListener {

	function handleChange(mql : MediaQueryList) : void;

} // end of MediaQueryListListener

native class Screen {

	__readonly__ var availWidth : int/*unsigned long*/;
	__readonly__ var availHeight : int/*unsigned long*/;
	__readonly__ var width : int/*unsigned long*/;
	__readonly__ var height : int/*unsigned long*/;
	__readonly__ var colorDepth : int/*unsigned long*/;
	__readonly__ var pixelDepth : int/*unsigned long*/;

} // end of Screen

native class CaretPosition {

	__readonly__ var offsetNode : Node;
	__readonly__ var offset : int/*unsigned long*/;

} // end of CaretPosition

native class ClientRectList {

	__readonly__ var length : int/*unsigned long*/;
	function __native_index_operator__(
		index : int/*unsigned long*/
	) : MayBeUndefined.<ClientRect>;
	function /* getter */ item(
		index : int/*unsigned long*/
	) : MayBeUndefined.<ClientRect>;

} // end of ClientRectList

native class ClientRect {

	__readonly__ var top : number/*float*/;
	__readonly__ var right : number/*float*/;
	__readonly__ var bottom : number/*float*/;
	__readonly__ var left : number/*float*/;
	__readonly__ var width : number/*float*/;
	__readonly__ var height : number/*float*/;

} // end of ClientRect

/*
end of generated files from:
	http://dev.w3.org/csswg/cssom/
	http://dev.w3.org/csswg/cssom-view/
	idl2jsx/extra/chrome.idl
	idl2jsx/extra/firefox.idl
*/

