// THIS FILE IS AUTOMATICALLY GENERATED.
/*
automatically generated from:
	http://www.w3.org/TR/DOM-Level-2-Views/idl/views.idl
*/
native __fake__ class AbstractView {

	__readonly__ var document : DocumentView;

} // end of AbstractView

native __fake__ class DocumentView {

	__readonly__ var defaultView : AbstractView;

} // end of DocumentView

/*
end of generated files from:
	http://www.w3.org/TR/DOM-Level-2-Views/idl/views.idl
*/

