// THIS FILE IS AUTOMATICALLY GENERATED.
/**

WebGL - OpenGL ES 2.0 for the Web

Specification:
    http://www.khronos.org/webgl/
    https://www.khronos.org/registry/webgl/specs/latest/
*/

import "./dom.jsx";
import "./html.jsx";
import "./canvas2d.jsx";
import "./typedarray.jsx";

/*
automatically generated from:
	https://www.khronos.org/registry/webgl/specs/latest/webgl.idl
*/
native class WebGLContextAttributes {

	var alpha : boolean;
	var depth : boolean;
	var stencil : boolean;
	var antialias : boolean;
	var premultipliedAlpha : boolean;
	var preserveDrawingBuffer : boolean;

} // end of WebGLContextAttributes

native class WebGLObject {
}

native class WebGLBuffer extends WebGLObject {
}

native class WebGLFramebuffer extends WebGLObject {
}

native class WebGLProgram extends WebGLObject {
}

native class WebGLRenderbuffer extends WebGLObject {
}

native class WebGLShader extends WebGLObject {
}

native class WebGLTexture extends WebGLObject {
}

native class WebGLUniformLocation {
}

native class WebGLActiveInfo {

	__readonly__ var size : int/*long*//*GLint*/;
	__readonly__ var type : int/*unsigned long*//*GLenum*/;
	__readonly__ var name : string/*DOMString*/;

} // end of WebGLActiveInfo

native class WebGLShaderPrecisionFormat {

	__readonly__ var rangeMin : int/*long*//*GLint*/;
	__readonly__ var rangeMax : int/*long*//*GLint*/;
	__readonly__ var precision : int/*long*//*GLint*/;

} // end of WebGLShaderPrecisionFormat

native class WebGLRenderingContext {

	/* ClearBufferMask */
	static const     DEPTH_BUFFER_BIT : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_BUFFER_BIT : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BUFFER_BIT : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BUFFER_BIT : int/*unsigned long*//*GLenum*/;
	static const     COLOR_BUFFER_BIT : int/*unsigned long*//*GLenum*/;
	__readonly__ var COLOR_BUFFER_BIT : int/*unsigned long*//*GLenum*/;
	/* BeginMode */
	static const     POINTS : int/*unsigned long*//*GLenum*/;
	__readonly__ var POINTS : int/*unsigned long*//*GLenum*/;
	static const     LINES : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINES : int/*unsigned long*//*GLenum*/;
	static const     LINE_LOOP : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINE_LOOP : int/*unsigned long*//*GLenum*/;
	static const     LINE_STRIP : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINE_STRIP : int/*unsigned long*//*GLenum*/;
	static const     TRIANGLES : int/*unsigned long*//*GLenum*/;
	__readonly__ var TRIANGLES : int/*unsigned long*//*GLenum*/;
	static const     TRIANGLE_STRIP : int/*unsigned long*//*GLenum*/;
	__readonly__ var TRIANGLE_STRIP : int/*unsigned long*//*GLenum*/;
	static const     TRIANGLE_FAN : int/*unsigned long*//*GLenum*/;
	__readonly__ var TRIANGLE_FAN : int/*unsigned long*//*GLenum*/;
	/* AlphaFunction (not supported in ES20) */
	/*      NEVER */
	/*      LESS */
	/*      EQUAL */
	/*      LEQUAL */
	/*      GREATER */
	/*      NOTEQUAL */
	/*      GEQUAL */
	/*      ALWAYS */

	/* BlendingFactorDest */
	static const     ZERO : int/*unsigned long*//*GLenum*/;
	__readonly__ var ZERO : int/*unsigned long*//*GLenum*/;
	static const     ONE : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE : int/*unsigned long*//*GLenum*/;
	static const     SRC_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var SRC_COLOR : int/*unsigned long*//*GLenum*/;
	static const     ONE_MINUS_SRC_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE_MINUS_SRC_COLOR : int/*unsigned long*//*GLenum*/;
	static const     SRC_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var SRC_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     ONE_MINUS_SRC_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE_MINUS_SRC_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     DST_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var DST_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     ONE_MINUS_DST_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE_MINUS_DST_ALPHA : int/*unsigned long*//*GLenum*/;
	/* BlendingFactorSrc */
	/*      ZERO */
	/*      ONE */
	static const     DST_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var DST_COLOR : int/*unsigned long*//*GLenum*/;
	static const     ONE_MINUS_DST_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE_MINUS_DST_COLOR : int/*unsigned long*//*GLenum*/;
	static const     SRC_ALPHA_SATURATE : int/*unsigned long*//*GLenum*/;
	__readonly__ var SRC_ALPHA_SATURATE : int/*unsigned long*//*GLenum*/;
	/*      SRC_ALPHA */
	/*      ONE_MINUS_SRC_ALPHA */
	/*      DST_ALPHA */
	/*      ONE_MINUS_DST_ALPHA */

	/* BlendEquationSeparate */
	static const     FUNC_ADD : int/*unsigned long*//*GLenum*/;
	__readonly__ var FUNC_ADD : int/*unsigned long*//*GLenum*/;
	static const     BLEND_EQUATION : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_EQUATION : int/*unsigned long*//*GLenum*/;
	static const     BLEND_EQUATION_RGB : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_EQUATION_RGB : int/*unsigned long*//*GLenum*/;
	/* same as BLEND_EQUATION */
	static const     BLEND_EQUATION_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_EQUATION_ALPHA : int/*unsigned long*//*GLenum*/;
	/* BlendSubtract */
	static const     FUNC_SUBTRACT : int/*unsigned long*//*GLenum*/;
	__readonly__ var FUNC_SUBTRACT : int/*unsigned long*//*GLenum*/;
	static const     FUNC_REVERSE_SUBTRACT : int/*unsigned long*//*GLenum*/;
	__readonly__ var FUNC_REVERSE_SUBTRACT : int/*unsigned long*//*GLenum*/;
	/* Separate Blend Functions */
	static const     BLEND_DST_RGB : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_DST_RGB : int/*unsigned long*//*GLenum*/;
	static const     BLEND_SRC_RGB : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_SRC_RGB : int/*unsigned long*//*GLenum*/;
	static const     BLEND_DST_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_DST_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     BLEND_SRC_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_SRC_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     CONSTANT_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var CONSTANT_COLOR : int/*unsigned long*//*GLenum*/;
	static const     ONE_MINUS_CONSTANT_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE_MINUS_CONSTANT_COLOR : int/*unsigned long*//*GLenum*/;
	static const     CONSTANT_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var CONSTANT_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     ONE_MINUS_CONSTANT_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var ONE_MINUS_CONSTANT_ALPHA : int/*unsigned long*//*GLenum*/;
	static const     BLEND_COLOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND_COLOR : int/*unsigned long*//*GLenum*/;
	/* Buffer Objects */
	static const     ARRAY_BUFFER : int/*unsigned long*//*GLenum*/;
	__readonly__ var ARRAY_BUFFER : int/*unsigned long*//*GLenum*/;
	static const     ELEMENT_ARRAY_BUFFER : int/*unsigned long*//*GLenum*/;
	__readonly__ var ELEMENT_ARRAY_BUFFER : int/*unsigned long*//*GLenum*/;
	static const     ARRAY_BUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	__readonly__ var ARRAY_BUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	static const     ELEMENT_ARRAY_BUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	__readonly__ var ELEMENT_ARRAY_BUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	static const     STREAM_DRAW : int/*unsigned long*//*GLenum*/;
	__readonly__ var STREAM_DRAW : int/*unsigned long*//*GLenum*/;
	static const     STATIC_DRAW : int/*unsigned long*//*GLenum*/;
	__readonly__ var STATIC_DRAW : int/*unsigned long*//*GLenum*/;
	static const     DYNAMIC_DRAW : int/*unsigned long*//*GLenum*/;
	__readonly__ var DYNAMIC_DRAW : int/*unsigned long*//*GLenum*/;
	static const     BUFFER_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var BUFFER_SIZE : int/*unsigned long*//*GLenum*/;
	static const     BUFFER_USAGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var BUFFER_USAGE : int/*unsigned long*//*GLenum*/;
	static const     CURRENT_VERTEX_ATTRIB : int/*unsigned long*//*GLenum*/;
	__readonly__ var CURRENT_VERTEX_ATTRIB : int/*unsigned long*//*GLenum*/;
	/* CullFaceMode */
	static const     FRONT : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRONT : int/*unsigned long*//*GLenum*/;
	static const     BACK : int/*unsigned long*//*GLenum*/;
	__readonly__ var BACK : int/*unsigned long*//*GLenum*/;
	static const     FRONT_AND_BACK : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRONT_AND_BACK : int/*unsigned long*//*GLenum*/;
	/* DepthFunction */
	/*      NEVER */
	/*      LESS */
	/*      EQUAL */
	/*      LEQUAL */
	/*      GREATER */
	/*      NOTEQUAL */
	/*      GEQUAL */
	/*      ALWAYS */

	/* EnableCap */
	/* TEXTURE_2D */
	static const     CULL_FACE : int/*unsigned long*//*GLenum*/;
	__readonly__ var CULL_FACE : int/*unsigned long*//*GLenum*/;
	static const     BLEND : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLEND : int/*unsigned long*//*GLenum*/;
	static const     DITHER : int/*unsigned long*//*GLenum*/;
	__readonly__ var DITHER : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_TEST : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_TEST : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_TEST : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_TEST : int/*unsigned long*//*GLenum*/;
	static const     SCISSOR_TEST : int/*unsigned long*//*GLenum*/;
	__readonly__ var SCISSOR_TEST : int/*unsigned long*//*GLenum*/;
	static const     POLYGON_OFFSET_FILL : int/*unsigned long*//*GLenum*/;
	__readonly__ var POLYGON_OFFSET_FILL : int/*unsigned long*//*GLenum*/;
	static const     SAMPLE_ALPHA_TO_COVERAGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLE_ALPHA_TO_COVERAGE : int/*unsigned long*//*GLenum*/;
	static const     SAMPLE_COVERAGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLE_COVERAGE : int/*unsigned long*//*GLenum*/;
	/* ErrorCode */
	static const     NO_ERROR : int/*unsigned long*//*GLenum*/;
	__readonly__ var NO_ERROR : int/*unsigned long*//*GLenum*/;
	static const     INVALID_ENUM : int/*unsigned long*//*GLenum*/;
	__readonly__ var INVALID_ENUM : int/*unsigned long*//*GLenum*/;
	static const     INVALID_VALUE : int/*unsigned long*//*GLenum*/;
	__readonly__ var INVALID_VALUE : int/*unsigned long*//*GLenum*/;
	static const     INVALID_OPERATION : int/*unsigned long*//*GLenum*/;
	__readonly__ var INVALID_OPERATION : int/*unsigned long*//*GLenum*/;
	static const     OUT_OF_MEMORY : int/*unsigned long*//*GLenum*/;
	__readonly__ var OUT_OF_MEMORY : int/*unsigned long*//*GLenum*/;
	/* FrontFaceDirection */
	static const     CW : int/*unsigned long*//*GLenum*/;
	__readonly__ var CW : int/*unsigned long*//*GLenum*/;
	static const     CCW : int/*unsigned long*//*GLenum*/;
	__readonly__ var CCW : int/*unsigned long*//*GLenum*/;
	/* GetPName */
	static const     LINE_WIDTH : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINE_WIDTH : int/*unsigned long*//*GLenum*/;
	static const     ALIASED_POINT_SIZE_RANGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var ALIASED_POINT_SIZE_RANGE : int/*unsigned long*//*GLenum*/;
	static const     ALIASED_LINE_WIDTH_RANGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var ALIASED_LINE_WIDTH_RANGE : int/*unsigned long*//*GLenum*/;
	static const     CULL_FACE_MODE : int/*unsigned long*//*GLenum*/;
	__readonly__ var CULL_FACE_MODE : int/*unsigned long*//*GLenum*/;
	static const     FRONT_FACE : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRONT_FACE : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_RANGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_RANGE : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_WRITEMASK : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_WRITEMASK : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_CLEAR_VALUE : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_CLEAR_VALUE : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_FUNC : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_FUNC : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_CLEAR_VALUE : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_CLEAR_VALUE : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_FUNC : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_FUNC : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_FAIL : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_FAIL : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_PASS_DEPTH_FAIL : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_PASS_DEPTH_FAIL : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_PASS_DEPTH_PASS : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_PASS_DEPTH_PASS : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_REF : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_REF : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_VALUE_MASK : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_VALUE_MASK : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_WRITEMASK : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_WRITEMASK : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_FUNC : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_FUNC : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_FAIL : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_FAIL : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_PASS_DEPTH_FAIL : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_PASS_DEPTH_FAIL : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_PASS_DEPTH_PASS : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_PASS_DEPTH_PASS : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_REF : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_REF : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_VALUE_MASK : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_VALUE_MASK : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BACK_WRITEMASK : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BACK_WRITEMASK : int/*unsigned long*//*GLenum*/;
	static const     VIEWPORT : int/*unsigned long*//*GLenum*/;
	__readonly__ var VIEWPORT : int/*unsigned long*//*GLenum*/;
	static const     SCISSOR_BOX : int/*unsigned long*//*GLenum*/;
	__readonly__ var SCISSOR_BOX : int/*unsigned long*//*GLenum*/;
	/*      SCISSOR_TEST */
	static const     COLOR_CLEAR_VALUE : int/*unsigned long*//*GLenum*/;
	__readonly__ var COLOR_CLEAR_VALUE : int/*unsigned long*//*GLenum*/;
	static const     COLOR_WRITEMASK : int/*unsigned long*//*GLenum*/;
	__readonly__ var COLOR_WRITEMASK : int/*unsigned long*//*GLenum*/;
	static const     UNPACK_ALIGNMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNPACK_ALIGNMENT : int/*unsigned long*//*GLenum*/;
	static const     PACK_ALIGNMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var PACK_ALIGNMENT : int/*unsigned long*//*GLenum*/;
	static const     MAX_TEXTURE_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_TEXTURE_SIZE : int/*unsigned long*//*GLenum*/;
	static const     MAX_VIEWPORT_DIMS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_VIEWPORT_DIMS : int/*unsigned long*//*GLenum*/;
	static const     SUBPIXEL_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var SUBPIXEL_BITS : int/*unsigned long*//*GLenum*/;
	static const     RED_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var RED_BITS : int/*unsigned long*//*GLenum*/;
	static const     GREEN_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var GREEN_BITS : int/*unsigned long*//*GLenum*/;
	static const     BLUE_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var BLUE_BITS : int/*unsigned long*//*GLenum*/;
	static const     ALPHA_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var ALPHA_BITS : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_BITS : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_BITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_BITS : int/*unsigned long*//*GLenum*/;
	static const     POLYGON_OFFSET_UNITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var POLYGON_OFFSET_UNITS : int/*unsigned long*//*GLenum*/;
	/*      POLYGON_OFFSET_FILL */
	static const     POLYGON_OFFSET_FACTOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var POLYGON_OFFSET_FACTOR : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_BINDING_2D : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_BINDING_2D : int/*unsigned long*//*GLenum*/;
	static const     SAMPLE_BUFFERS : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLE_BUFFERS : int/*unsigned long*//*GLenum*/;
	static const     SAMPLES : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLES : int/*unsigned long*//*GLenum*/;
	static const     SAMPLE_COVERAGE_VALUE : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLE_COVERAGE_VALUE : int/*unsigned long*//*GLenum*/;
	static const     SAMPLE_COVERAGE_INVERT : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLE_COVERAGE_INVERT : int/*unsigned long*//*GLenum*/;
	/* GetTextureParameter */
	/*      TEXTURE_MAG_FILTER */
	/*      TEXTURE_MIN_FILTER */
	/*      TEXTURE_WRAP_S */
	/*      TEXTURE_WRAP_T */

	static const     COMPRESSED_TEXTURE_FORMATS : int/*unsigned long*//*GLenum*/;
	__readonly__ var COMPRESSED_TEXTURE_FORMATS : int/*unsigned long*//*GLenum*/;
	/* HintMode */
	static const     DONT_CARE : int/*unsigned long*//*GLenum*/;
	__readonly__ var DONT_CARE : int/*unsigned long*//*GLenum*/;
	static const     FASTEST : int/*unsigned long*//*GLenum*/;
	__readonly__ var FASTEST : int/*unsigned long*//*GLenum*/;
	static const     NICEST : int/*unsigned long*//*GLenum*/;
	__readonly__ var NICEST : int/*unsigned long*//*GLenum*/;
	/* HintTarget */
	static const     GENERATE_MIPMAP_HINT : int/*unsigned long*//*GLenum*/;
	__readonly__ var GENERATE_MIPMAP_HINT : int/*unsigned long*//*GLenum*/;
	/* DataType */
	static const     BYTE : int/*unsigned long*//*GLenum*/;
	__readonly__ var BYTE : int/*unsigned long*//*GLenum*/;
	static const     UNSIGNED_BYTE : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNSIGNED_BYTE : int/*unsigned long*//*GLenum*/;
	static const     SHORT : int/*unsigned long*//*GLenum*/;
	__readonly__ var SHORT : int/*unsigned long*//*GLenum*/;
	static const     UNSIGNED_SHORT : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNSIGNED_SHORT : int/*unsigned long*//*GLenum*/;
	static const     INT : int/*unsigned long*//*GLenum*/;
	__readonly__ var INT : int/*unsigned long*//*GLenum*/;
	static const     UNSIGNED_INT : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNSIGNED_INT : int/*unsigned long*//*GLenum*/;
	static const     FLOAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT : int/*unsigned long*//*GLenum*/;
	/* PixelFormat */
	static const     DEPTH_COMPONENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_COMPONENT : int/*unsigned long*//*GLenum*/;
	static const     ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var ALPHA : int/*unsigned long*//*GLenum*/;
	static const     RGB : int/*unsigned long*//*GLenum*/;
	__readonly__ var RGB : int/*unsigned long*//*GLenum*/;
	static const     RGBA : int/*unsigned long*//*GLenum*/;
	__readonly__ var RGBA : int/*unsigned long*//*GLenum*/;
	static const     LUMINANCE : int/*unsigned long*//*GLenum*/;
	__readonly__ var LUMINANCE : int/*unsigned long*//*GLenum*/;
	static const     LUMINANCE_ALPHA : int/*unsigned long*//*GLenum*/;
	__readonly__ var LUMINANCE_ALPHA : int/*unsigned long*//*GLenum*/;
	/* PixelType */
	/*      UNSIGNED_BYTE */
	static const     UNSIGNED_SHORT_4_4_4_4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNSIGNED_SHORT_4_4_4_4 : int/*unsigned long*//*GLenum*/;
	static const     UNSIGNED_SHORT_5_5_5_1 : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNSIGNED_SHORT_5_5_5_1 : int/*unsigned long*//*GLenum*/;
	static const     UNSIGNED_SHORT_5_6_5 : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNSIGNED_SHORT_5_6_5 : int/*unsigned long*//*GLenum*/;
	/* Shaders */
	static const     FRAGMENT_SHADER : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAGMENT_SHADER : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_SHADER : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_SHADER : int/*unsigned long*//*GLenum*/;
	static const     MAX_VERTEX_ATTRIBS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_VERTEX_ATTRIBS : int/*unsigned long*//*GLenum*/;
	static const     MAX_VERTEX_UNIFORM_VECTORS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_VERTEX_UNIFORM_VECTORS : int/*unsigned long*//*GLenum*/;
	static const     MAX_VARYING_VECTORS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_VARYING_VECTORS : int/*unsigned long*//*GLenum*/;
	static const     MAX_COMBINED_TEXTURE_IMAGE_UNITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_COMBINED_TEXTURE_IMAGE_UNITS : int/*unsigned long*//*GLenum*/;
	static const     MAX_VERTEX_TEXTURE_IMAGE_UNITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_VERTEX_TEXTURE_IMAGE_UNITS : int/*unsigned long*//*GLenum*/;
	static const     MAX_TEXTURE_IMAGE_UNITS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_TEXTURE_IMAGE_UNITS : int/*unsigned long*//*GLenum*/;
	static const     MAX_FRAGMENT_UNIFORM_VECTORS : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_FRAGMENT_UNIFORM_VECTORS : int/*unsigned long*//*GLenum*/;
	static const     SHADER_TYPE : int/*unsigned long*//*GLenum*/;
	__readonly__ var SHADER_TYPE : int/*unsigned long*//*GLenum*/;
	static const     DELETE_STATUS : int/*unsigned long*//*GLenum*/;
	__readonly__ var DELETE_STATUS : int/*unsigned long*//*GLenum*/;
	static const     LINK_STATUS : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINK_STATUS : int/*unsigned long*//*GLenum*/;
	static const     VALIDATE_STATUS : int/*unsigned long*//*GLenum*/;
	__readonly__ var VALIDATE_STATUS : int/*unsigned long*//*GLenum*/;
	static const     ATTACHED_SHADERS : int/*unsigned long*//*GLenum*/;
	__readonly__ var ATTACHED_SHADERS : int/*unsigned long*//*GLenum*/;
	static const     ACTIVE_UNIFORMS : int/*unsigned long*//*GLenum*/;
	__readonly__ var ACTIVE_UNIFORMS : int/*unsigned long*//*GLenum*/;
	static const     ACTIVE_ATTRIBUTES : int/*unsigned long*//*GLenum*/;
	__readonly__ var ACTIVE_ATTRIBUTES : int/*unsigned long*//*GLenum*/;
	static const     SHADING_LANGUAGE_VERSION : int/*unsigned long*//*GLenum*/;
	__readonly__ var SHADING_LANGUAGE_VERSION : int/*unsigned long*//*GLenum*/;
	static const     CURRENT_PROGRAM : int/*unsigned long*//*GLenum*/;
	__readonly__ var CURRENT_PROGRAM : int/*unsigned long*//*GLenum*/;
	/* StencilFunction */
	static const     NEVER : int/*unsigned long*//*GLenum*/;
	__readonly__ var NEVER : int/*unsigned long*//*GLenum*/;
	static const     LESS : int/*unsigned long*//*GLenum*/;
	__readonly__ var LESS : int/*unsigned long*//*GLenum*/;
	static const     EQUAL : int/*unsigned long*//*GLenum*/;
	__readonly__ var EQUAL : int/*unsigned long*//*GLenum*/;
	static const     LEQUAL : int/*unsigned long*//*GLenum*/;
	__readonly__ var LEQUAL : int/*unsigned long*//*GLenum*/;
	static const     GREATER : int/*unsigned long*//*GLenum*/;
	__readonly__ var GREATER : int/*unsigned long*//*GLenum*/;
	static const     NOTEQUAL : int/*unsigned long*//*GLenum*/;
	__readonly__ var NOTEQUAL : int/*unsigned long*//*GLenum*/;
	static const     GEQUAL : int/*unsigned long*//*GLenum*/;
	__readonly__ var GEQUAL : int/*unsigned long*//*GLenum*/;
	static const     ALWAYS : int/*unsigned long*//*GLenum*/;
	__readonly__ var ALWAYS : int/*unsigned long*//*GLenum*/;
	/* StencilOp */
	/*      ZERO */
	static const     KEEP : int/*unsigned long*//*GLenum*/;
	__readonly__ var KEEP : int/*unsigned long*//*GLenum*/;
	static const     REPLACE : int/*unsigned long*//*GLenum*/;
	__readonly__ var REPLACE : int/*unsigned long*//*GLenum*/;
	static const     INCR : int/*unsigned long*//*GLenum*/;
	__readonly__ var INCR : int/*unsigned long*//*GLenum*/;
	static const     DECR : int/*unsigned long*//*GLenum*/;
	__readonly__ var DECR : int/*unsigned long*//*GLenum*/;
	static const     INVERT : int/*unsigned long*//*GLenum*/;
	__readonly__ var INVERT : int/*unsigned long*//*GLenum*/;
	static const     INCR_WRAP : int/*unsigned long*//*GLenum*/;
	__readonly__ var INCR_WRAP : int/*unsigned long*//*GLenum*/;
	static const     DECR_WRAP : int/*unsigned long*//*GLenum*/;
	__readonly__ var DECR_WRAP : int/*unsigned long*//*GLenum*/;
	/* StringName */
	static const     VENDOR : int/*unsigned long*//*GLenum*/;
	__readonly__ var VENDOR : int/*unsigned long*//*GLenum*/;
	static const     RENDERER : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERER : int/*unsigned long*//*GLenum*/;
	static const     VERSION : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERSION : int/*unsigned long*//*GLenum*/;
	/* TextureMagFilter */
	static const     NEAREST : int/*unsigned long*//*GLenum*/;
	__readonly__ var NEAREST : int/*unsigned long*//*GLenum*/;
	static const     LINEAR : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINEAR : int/*unsigned long*//*GLenum*/;
	/* TextureMinFilter */
	/*      NEAREST */
	/*      LINEAR */
	static const     NEAREST_MIPMAP_NEAREST : int/*unsigned long*//*GLenum*/;
	__readonly__ var NEAREST_MIPMAP_NEAREST : int/*unsigned long*//*GLenum*/;
	static const     LINEAR_MIPMAP_NEAREST : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINEAR_MIPMAP_NEAREST : int/*unsigned long*//*GLenum*/;
	static const     NEAREST_MIPMAP_LINEAR : int/*unsigned long*//*GLenum*/;
	__readonly__ var NEAREST_MIPMAP_LINEAR : int/*unsigned long*//*GLenum*/;
	static const     LINEAR_MIPMAP_LINEAR : int/*unsigned long*//*GLenum*/;
	__readonly__ var LINEAR_MIPMAP_LINEAR : int/*unsigned long*//*GLenum*/;
	/* TextureParameterName */
	static const     TEXTURE_MAG_FILTER : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_MAG_FILTER : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_MIN_FILTER : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_MIN_FILTER : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_WRAP_S : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_WRAP_S : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_WRAP_T : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_WRAP_T : int/*unsigned long*//*GLenum*/;
	/* TextureTarget */
	static const     TEXTURE_2D : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_2D : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_BINDING_CUBE_MAP : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_BINDING_CUBE_MAP : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP_POSITIVE_X : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP_POSITIVE_X : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP_NEGATIVE_X : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP_NEGATIVE_X : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP_POSITIVE_Y : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP_POSITIVE_Y : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP_NEGATIVE_Y : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP_NEGATIVE_Y : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP_POSITIVE_Z : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP_POSITIVE_Z : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE_CUBE_MAP_NEGATIVE_Z : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE_CUBE_MAP_NEGATIVE_Z : int/*unsigned long*//*GLenum*/;
	static const     MAX_CUBE_MAP_TEXTURE_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_CUBE_MAP_TEXTURE_SIZE : int/*unsigned long*//*GLenum*/;
	/* TextureUnit */
	static const     TEXTURE0 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE0 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE1 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE1 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE2 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE2 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE3 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE3 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE4 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE5 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE5 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE6 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE6 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE7 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE7 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE8 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE8 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE9 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE9 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE10 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE10 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE11 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE11 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE12 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE12 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE13 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE13 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE14 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE14 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE15 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE15 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE16 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE16 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE17 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE17 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE18 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE18 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE19 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE19 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE20 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE20 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE21 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE21 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE22 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE22 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE23 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE23 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE24 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE24 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE25 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE25 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE26 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE26 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE27 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE27 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE28 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE28 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE29 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE29 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE30 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE30 : int/*unsigned long*//*GLenum*/;
	static const     TEXTURE31 : int/*unsigned long*//*GLenum*/;
	__readonly__ var TEXTURE31 : int/*unsigned long*//*GLenum*/;
	static const     ACTIVE_TEXTURE : int/*unsigned long*//*GLenum*/;
	__readonly__ var ACTIVE_TEXTURE : int/*unsigned long*//*GLenum*/;
	/* TextureWrapMode */
	static const     REPEAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var REPEAT : int/*unsigned long*//*GLenum*/;
	static const     CLAMP_TO_EDGE : int/*unsigned long*//*GLenum*/;
	__readonly__ var CLAMP_TO_EDGE : int/*unsigned long*//*GLenum*/;
	static const     MIRRORED_REPEAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var MIRRORED_REPEAT : int/*unsigned long*//*GLenum*/;
	/* Uniform Types */
	static const     FLOAT_VEC2 : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT_VEC2 : int/*unsigned long*//*GLenum*/;
	static const     FLOAT_VEC3 : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT_VEC3 : int/*unsigned long*//*GLenum*/;
	static const     FLOAT_VEC4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT_VEC4 : int/*unsigned long*//*GLenum*/;
	static const     INT_VEC2 : int/*unsigned long*//*GLenum*/;
	__readonly__ var INT_VEC2 : int/*unsigned long*//*GLenum*/;
	static const     INT_VEC3 : int/*unsigned long*//*GLenum*/;
	__readonly__ var INT_VEC3 : int/*unsigned long*//*GLenum*/;
	static const     INT_VEC4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var INT_VEC4 : int/*unsigned long*//*GLenum*/;
	static const     BOOL : int/*unsigned long*//*GLenum*/;
	__readonly__ var BOOL : int/*unsigned long*//*GLenum*/;
	static const     BOOL_VEC2 : int/*unsigned long*//*GLenum*/;
	__readonly__ var BOOL_VEC2 : int/*unsigned long*//*GLenum*/;
	static const     BOOL_VEC3 : int/*unsigned long*//*GLenum*/;
	__readonly__ var BOOL_VEC3 : int/*unsigned long*//*GLenum*/;
	static const     BOOL_VEC4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var BOOL_VEC4 : int/*unsigned long*//*GLenum*/;
	static const     FLOAT_MAT2 : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT_MAT2 : int/*unsigned long*//*GLenum*/;
	static const     FLOAT_MAT3 : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT_MAT3 : int/*unsigned long*//*GLenum*/;
	static const     FLOAT_MAT4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var FLOAT_MAT4 : int/*unsigned long*//*GLenum*/;
	static const     SAMPLER_2D : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLER_2D : int/*unsigned long*//*GLenum*/;
	static const     SAMPLER_CUBE : int/*unsigned long*//*GLenum*/;
	__readonly__ var SAMPLER_CUBE : int/*unsigned long*//*GLenum*/;
	/* Vertex Arrays */
	static const     VERTEX_ATTRIB_ARRAY_ENABLED : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_ENABLED : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_ATTRIB_ARRAY_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_SIZE : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_ATTRIB_ARRAY_STRIDE : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_STRIDE : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_ATTRIB_ARRAY_TYPE : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_TYPE : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_ATTRIB_ARRAY_NORMALIZED : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_NORMALIZED : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_ATTRIB_ARRAY_POINTER : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_POINTER : int/*unsigned long*//*GLenum*/;
	static const     VERTEX_ATTRIB_ARRAY_BUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	__readonly__ var VERTEX_ATTRIB_ARRAY_BUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	/* Shader Source */
	static const     COMPILE_STATUS : int/*unsigned long*//*GLenum*/;
	__readonly__ var COMPILE_STATUS : int/*unsigned long*//*GLenum*/;
	/* Shader Precision-Specified Types */
	static const     LOW_FLOAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var LOW_FLOAT : int/*unsigned long*//*GLenum*/;
	static const     MEDIUM_FLOAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var MEDIUM_FLOAT : int/*unsigned long*//*GLenum*/;
	static const     HIGH_FLOAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var HIGH_FLOAT : int/*unsigned long*//*GLenum*/;
	static const     LOW_INT : int/*unsigned long*//*GLenum*/;
	__readonly__ var LOW_INT : int/*unsigned long*//*GLenum*/;
	static const     MEDIUM_INT : int/*unsigned long*//*GLenum*/;
	__readonly__ var MEDIUM_INT : int/*unsigned long*//*GLenum*/;
	static const     HIGH_INT : int/*unsigned long*//*GLenum*/;
	__readonly__ var HIGH_INT : int/*unsigned long*//*GLenum*/;
	/* Framebuffer Object. */
	static const     FRAMEBUFFER : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER : int/*unsigned long*//*GLenum*/;
	static const     RGBA4 : int/*unsigned long*//*GLenum*/;
	__readonly__ var RGBA4 : int/*unsigned long*//*GLenum*/;
	static const     RGB5_A1 : int/*unsigned long*//*GLenum*/;
	__readonly__ var RGB5_A1 : int/*unsigned long*//*GLenum*/;
	static const     RGB565 : int/*unsigned long*//*GLenum*/;
	__readonly__ var RGB565 : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_COMPONENT16 : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_COMPONENT16 : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_INDEX : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_INDEX : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_INDEX8 : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_INDEX8 : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_STENCIL : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_STENCIL : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_WIDTH : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_WIDTH : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_HEIGHT : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_HEIGHT : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_INTERNAL_FORMAT : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_INTERNAL_FORMAT : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_RED_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_RED_SIZE : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_GREEN_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_GREEN_SIZE : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_BLUE_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_BLUE_SIZE : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_ALPHA_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_ALPHA_SIZE : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_DEPTH_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_DEPTH_SIZE : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_STENCIL_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_STENCIL_SIZE : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_ATTACHMENT_OBJECT_NAME : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_ATTACHMENT_OBJECT_NAME : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE : int/*unsigned long*//*GLenum*/;
	static const     COLOR_ATTACHMENT0 : int/*unsigned long*//*GLenum*/;
	__readonly__ var COLOR_ATTACHMENT0 : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	static const     STENCIL_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var STENCIL_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	static const     DEPTH_STENCIL_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var DEPTH_STENCIL_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	static const     NONE : int/*unsigned long*//*GLenum*/;
	__readonly__ var NONE : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_COMPLETE : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_COMPLETE : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_INCOMPLETE_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_INCOMPLETE_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_INCOMPLETE_DIMENSIONS : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_INCOMPLETE_DIMENSIONS : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_UNSUPPORTED : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_UNSUPPORTED : int/*unsigned long*//*GLenum*/;
	static const     FRAMEBUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	__readonly__ var FRAMEBUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	static const     RENDERBUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	__readonly__ var RENDERBUFFER_BINDING : int/*unsigned long*//*GLenum*/;
	static const     MAX_RENDERBUFFER_SIZE : int/*unsigned long*//*GLenum*/;
	__readonly__ var MAX_RENDERBUFFER_SIZE : int/*unsigned long*//*GLenum*/;
	static const     INVALID_FRAMEBUFFER_OPERATION : int/*unsigned long*//*GLenum*/;
	__readonly__ var INVALID_FRAMEBUFFER_OPERATION : int/*unsigned long*//*GLenum*/;
	/* WebGL-specific enums */
	static const     UNPACK_FLIP_Y_WEBGL : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNPACK_FLIP_Y_WEBGL : int/*unsigned long*//*GLenum*/;
	static const     UNPACK_PREMULTIPLY_ALPHA_WEBGL : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNPACK_PREMULTIPLY_ALPHA_WEBGL : int/*unsigned long*//*GLenum*/;
	static const     CONTEXT_LOST_WEBGL : int/*unsigned long*//*GLenum*/;
	__readonly__ var CONTEXT_LOST_WEBGL : int/*unsigned long*//*GLenum*/;
	static const     UNPACK_COLORSPACE_CONVERSION_WEBGL : int/*unsigned long*//*GLenum*/;
	__readonly__ var UNPACK_COLORSPACE_CONVERSION_WEBGL : int/*unsigned long*//*GLenum*/;
	static const     BROWSER_DEFAULT_WEBGL : int/*unsigned long*//*GLenum*/;
	__readonly__ var BROWSER_DEFAULT_WEBGL : int/*unsigned long*//*GLenum*/;
	__readonly__ var canvas : HTMLCanvasElement;
	__readonly__ var drawingBufferWidth : int/*long*//*GLsizei*/;
	__readonly__ var drawingBufferHeight : int/*long*//*GLsizei*/;
	function getContextAttributes() : WebGLContextAttributes;
	function isContextLost() : boolean;
	function getSupportedExtensions() : string[]/*sequence<DOMString>?*/;
	function getExtension(
		name : string/*DOMString*/
	) : Object/*object?*/;
	function activeTexture(
		texture : int/*unsigned long*//*GLenum*/
	) : void;
	function attachShader(
		program : WebGLProgram,
		shader : WebGLShader
	) : void;
	function bindAttribLocation(
		program : WebGLProgram,
		index : int/*unsigned long*//*GLuint*/,
		name : string/*DOMString*/
	) : void;
	function bindBuffer(
		target : int/*unsigned long*//*GLenum*/,
		buffer : WebGLBuffer
	) : void;
	function bindFramebuffer(
		target : int/*unsigned long*//*GLenum*/,
		framebuffer : WebGLFramebuffer
	) : void;
	function bindRenderbuffer(
		target : int/*unsigned long*//*GLenum*/,
		renderbuffer : WebGLRenderbuffer
	) : void;
	function bindTexture(
		target : int/*unsigned long*//*GLenum*/,
		texture : WebGLTexture
	) : void;
	function blendColor(
		red : number/*float*//*GLclampf*/,
		green : number/*float*//*GLclampf*/,
		blue : number/*float*//*GLclampf*/,
		alpha : number/*float*//*GLclampf*/
	) : void;
	function blendEquation(
		mode : int/*unsigned long*//*GLenum*/
	) : void;
	function blendEquationSeparate(
		modeRGB : int/*unsigned long*//*GLenum*/,
		modeAlpha : int/*unsigned long*//*GLenum*/
	) : void;
	function blendFunc(
		sfactor : int/*unsigned long*//*GLenum*/,
		dfactor : int/*unsigned long*//*GLenum*/
	) : void;
	function blendFuncSeparate(
		srcRGB : int/*unsigned long*//*GLenum*/,
		dstRGB : int/*unsigned long*//*GLenum*/,
		srcAlpha : int/*unsigned long*//*GLenum*/,
		dstAlpha : int/*unsigned long*//*GLenum*/
	) : void;
	function bufferData(
		target : int/*unsigned long*//*GLenum*/,
		size : number/*long long*//*GLsizeiptr*/,
		usage : int/*unsigned long*//*GLenum*/
	) : void;
	function bufferData(
		target : int/*unsigned long*//*GLenum*/,
		data : ArrayBufferView,
		usage : int/*unsigned long*//*GLenum*/
	) : void;
	function bufferData(
		target : int/*unsigned long*//*GLenum*/,
		data : ArrayBuffer,
		usage : int/*unsigned long*//*GLenum*/
	) : void;
	function bufferSubData(
		target : int/*unsigned long*//*GLenum*/,
		offset : number/*long long*//*GLintptr*/,
		data : ArrayBufferView
	) : void;
	function bufferSubData(
		target : int/*unsigned long*//*GLenum*/,
		offset : number/*long long*//*GLintptr*/,
		data : ArrayBuffer
	) : void;
	function checkFramebufferStatus(
		target : int/*unsigned long*//*GLenum*/
	) : int/*unsigned long*//*GLenum*/;
	function clear(mask : int/*unsigned long*//*GLbitfield*/) : void;
	function clearColor(
		red : number/*float*//*GLclampf*/,
		green : number/*float*//*GLclampf*/,
		blue : number/*float*//*GLclampf*/,
		alpha : number/*float*//*GLclampf*/
	) : void;
	function clearDepth(depth : number/*float*//*GLclampf*/) : void;
	function clearStencil(s : int/*long*//*GLint*/) : void;
	function colorMask(
		red : boolean/*GLboolean*/,
		green : boolean/*GLboolean*/,
		blue : boolean/*GLboolean*/,
		alpha : boolean/*GLboolean*/
	) : void;
	function compileShader(shader : WebGLShader) : void;
	function compressedTexImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/,
		border : int/*long*//*GLint*/,
		data : ArrayBufferView
	) : void;
	function compressedTexSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/,
		format : int/*unsigned long*//*GLenum*/,
		data : ArrayBufferView
	) : void;
	function copyTexImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/,
		border : int/*long*//*GLint*/
	) : void;
	function copyTexSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/
	) : void;
	function createBuffer() : WebGLBuffer;
	function createFramebuffer() : WebGLFramebuffer;
	function createProgram() : WebGLProgram;
	function createRenderbuffer() : WebGLRenderbuffer;
	function createShader(
		type : int/*unsigned long*//*GLenum*/
	) : WebGLShader;
	function createTexture() : WebGLTexture;
	function cullFace(mode : int/*unsigned long*//*GLenum*/) : void;
	function deleteBuffer(buffer : WebGLBuffer) : void;
	function deleteFramebuffer(framebuffer : WebGLFramebuffer) : void;
	function deleteProgram(program : WebGLProgram) : void;
	function deleteRenderbuffer(
		renderbuffer : WebGLRenderbuffer
	) : void;
	function deleteShader(shader : WebGLShader) : void;
	function deleteTexture(texture : WebGLTexture) : void;
	function depthFunc(func : int/*unsigned long*//*GLenum*/) : void;
	function depthMask(flag : boolean/*GLboolean*/) : void;
	function depthRange(
		zNear : number/*float*//*GLclampf*/,
		zFar : number/*float*//*GLclampf*/
	) : void;
	function detachShader(
		program : WebGLProgram,
		shader : WebGLShader
	) : void;
	function disable(cap : int/*unsigned long*//*GLenum*/) : void;
	function disableVertexAttribArray(
		index : int/*unsigned long*//*GLuint*/
	) : void;
	function drawArrays(
		mode : int/*unsigned long*//*GLenum*/,
		first : int/*long*//*GLint*/,
		count : int/*long*//*GLsizei*/
	) : void;
	function drawElements(
		mode : int/*unsigned long*//*GLenum*/,
		count : int/*long*//*GLsizei*/,
		type : int/*unsigned long*//*GLenum*/,
		offset : number/*long long*//*GLintptr*/
	) : void;
	function enable(cap : int/*unsigned long*//*GLenum*/) : void;
	function enableVertexAttribArray(
		index : int/*unsigned long*//*GLuint*/
	) : void;
	function finish() : void;
	function flush() : void;
	function framebufferRenderbuffer(
		target : int/*unsigned long*//*GLenum*/,
		attachment : int/*unsigned long*//*GLenum*/,
		renderbuffertarget : int/*unsigned long*//*GLenum*/,
		renderbuffer : WebGLRenderbuffer
	) : void;
	function framebufferTexture2D(
		target : int/*unsigned long*//*GLenum*/,
		attachment : int/*unsigned long*//*GLenum*/,
		textarget : int/*unsigned long*//*GLenum*/,
		texture : WebGLTexture,
		level : int/*long*//*GLint*/
	) : void;
	function frontFace(mode : int/*unsigned long*//*GLenum*/) : void;
	function generateMipmap(
		target : int/*unsigned long*//*GLenum*/
	) : void;
	function getActiveAttrib(
		program : WebGLProgram,
		index : int/*unsigned long*//*GLuint*/
	) : WebGLActiveInfo;
	function getActiveUniform(
		program : WebGLProgram,
		index : int/*unsigned long*//*GLuint*/
	) : WebGLActiveInfo;
	function getAttachedShaders(program : WebGLProgram) : WebGLShader[];
	function getAttribLocation(
		program : WebGLProgram,
		name : string/*DOMString*/
	) : int/*long*//*GLint*/;
	function getBufferParameter(
		target : int/*unsigned long*//*GLenum*/,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getParameter(
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getError() : int/*unsigned long*//*GLenum*/;
	function getFramebufferAttachmentParameter(
		target : int/*unsigned long*//*GLenum*/,
		attachment : int/*unsigned long*//*GLenum*/,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getProgramParameter(
		program : WebGLProgram,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getProgramInfoLog(
		program : WebGLProgram
	) : string/*DOMString?*/;
	function getRenderbufferParameter(
		target : int/*unsigned long*//*GLenum*/,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getShaderParameter(
		shader : WebGLShader,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getShaderPrecisionFormat(
		shadertype : int/*unsigned long*//*GLenum*/,
		precisiontype : int/*unsigned long*//*GLenum*/
	) : WebGLShaderPrecisionFormat;
	function getShaderInfoLog(
		shader : WebGLShader
	) : string/*DOMString?*/;
	function getShaderSource(
		shader : WebGLShader
	) : string/*DOMString?*/;
	function getTexParameter(
		target : int/*unsigned long*//*GLenum*/,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getUniform(
		program : WebGLProgram,
		location : WebGLUniformLocation
	) : variant/*any*/;
	function getUniformLocation(
		program : WebGLProgram,
		name : string/*DOMString*/
	) : WebGLUniformLocation;
	function getVertexAttrib(
		index : int/*unsigned long*//*GLuint*/,
		pname : int/*unsigned long*//*GLenum*/
	) : variant/*any*/;
	function getVertexAttribOffset(
		index : int/*unsigned long*//*GLuint*/,
		pname : int/*unsigned long*//*GLenum*/
	) : number/*long long*//*GLsizeiptr*/;
	function hint(
		target : int/*unsigned long*//*GLenum*/,
		mode : int/*unsigned long*//*GLenum*/
	) : void;
	function isBuffer(buffer : WebGLBuffer) : boolean/*GLboolean*/;
	function isEnabled(
		cap : int/*unsigned long*//*GLenum*/
	) : boolean/*GLboolean*/;
	function isFramebuffer(
		framebuffer : WebGLFramebuffer
	) : boolean/*GLboolean*/;
	function isProgram(program : WebGLProgram) : boolean/*GLboolean*/;
	function isRenderbuffer(
		renderbuffer : WebGLRenderbuffer
	) : boolean/*GLboolean*/;
	function isShader(shader : WebGLShader) : boolean/*GLboolean*/;
	function isTexture(texture : WebGLTexture) : boolean/*GLboolean*/;
	function lineWidth(width : number/*float*//*GLfloat*/) : void;
	function linkProgram(program : WebGLProgram) : void;
	function pixelStorei(
		pname : int/*unsigned long*//*GLenum*/,
		param : int/*long*//*GLint*/
	) : void;
	function polygonOffset(
		factor : number/*float*//*GLfloat*/,
		units : number/*float*//*GLfloat*/
	) : void;
	function readPixels(
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		pixels : ArrayBufferView
	) : void;
	function renderbufferStorage(
		target : int/*unsigned long*//*GLenum*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/
	) : void;
	function sampleCoverage(
		value : number/*float*//*GLclampf*/,
		invert : boolean/*GLboolean*/
	) : void;
	function scissor(
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/
	) : void;
	function shaderSource(
		shader : WebGLShader,
		source : string/*DOMString*/
	) : void;
	function stencilFunc(
		func : int/*unsigned long*//*GLenum*/,
		ref : int/*long*//*GLint*/,
		mask : int/*unsigned long*//*GLuint*/
	) : void;
	function stencilFuncSeparate(
		face : int/*unsigned long*//*GLenum*/,
		func : int/*unsigned long*//*GLenum*/,
		ref : int/*long*//*GLint*/,
		mask : int/*unsigned long*//*GLuint*/
	) : void;
	function stencilMask(mask : int/*unsigned long*//*GLuint*/) : void;
	function stencilMaskSeparate(
		face : int/*unsigned long*//*GLenum*/,
		mask : int/*unsigned long*//*GLuint*/
	) : void;
	function stencilOp(
		fail : int/*unsigned long*//*GLenum*/,
		zfail : int/*unsigned long*//*GLenum*/,
		zpass : int/*unsigned long*//*GLenum*/
	) : void;
	function stencilOpSeparate(
		face : int/*unsigned long*//*GLenum*/,
		fail : int/*unsigned long*//*GLenum*/,
		zfail : int/*unsigned long*//*GLenum*/,
		zpass : int/*unsigned long*//*GLenum*/
	) : void;
	function texImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/,
		border : int/*long*//*GLint*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		pixels : ArrayBufferView
	) : void;
	function texImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		pixels : ImageData
	) : void;
	function texImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		image : HTMLImageElement
	) : void;
	// May throw DOMException
	function texImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		canvas : HTMLCanvasElement
	) : void;
	// May throw DOMException
	function texImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		internalformat : int/*unsigned long*//*GLenum*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		video : HTMLVideoElement
	) : void;
	// May throw DOMException

	function texParameterf(
		target : int/*unsigned long*//*GLenum*/,
		pname : int/*unsigned long*//*GLenum*/,
		param : number/*float*//*GLfloat*/
	) : void;
	function texParameteri(
		target : int/*unsigned long*//*GLenum*/,
		pname : int/*unsigned long*//*GLenum*/,
		param : int/*long*//*GLint*/
	) : void;
	function texSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		pixels : ArrayBufferView
	) : void;
	function texSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		pixels : ImageData
	) : void;
	function texSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		image : HTMLImageElement
	) : void;
	// May throw DOMException
	function texSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		canvas : HTMLCanvasElement
	) : void;
	// May throw DOMException
	function texSubImage2D(
		target : int/*unsigned long*//*GLenum*/,
		level : int/*long*//*GLint*/,
		xoffset : int/*long*//*GLint*/,
		yoffset : int/*long*//*GLint*/,
		format : int/*unsigned long*//*GLenum*/,
		type : int/*unsigned long*//*GLenum*/,
		video : HTMLVideoElement
	) : void;
	// May throw DOMException

	function uniform1f(
		location : WebGLUniformLocation,
		x : number/*float*//*GLfloat*/
	) : void;
	function uniform1fv(
		location : WebGLUniformLocation,
		v : Float32Array
	) : void;
	function uniform1fv(
		location : WebGLUniformLocation,
		v : number[]/*sequence<float>*/
	) : void;
	function uniform1i(
		location : WebGLUniformLocation,
		x : int/*long*//*GLint*/
	) : void;
	function uniform1iv(
		location : WebGLUniformLocation,
		v : Int32Array
	) : void;
	function uniform1iv(
		location : WebGLUniformLocation,
		v : int[]/*sequence<long>*/
	) : void;
	function uniform1iv(
		location : WebGLUniformLocation,
		v : number[]
	) : void;
	function uniform2f(
		location : WebGLUniformLocation,
		x : number/*float*//*GLfloat*/,
		y : number/*float*//*GLfloat*/
	) : void;
	function uniform2fv(
		location : WebGLUniformLocation,
		v : Float32Array
	) : void;
	function uniform2fv(
		location : WebGLUniformLocation,
		v : number[]/*sequence<float>*/
	) : void;
	function uniform2i(
		location : WebGLUniformLocation,
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/
	) : void;
	function uniform2iv(
		location : WebGLUniformLocation,
		v : Int32Array
	) : void;
	function uniform2iv(
		location : WebGLUniformLocation,
		v : int[]/*sequence<long>*/
	) : void;
	function uniform2iv(
		location : WebGLUniformLocation,
		v : number[]
	) : void;
	function uniform3f(
		location : WebGLUniformLocation,
		x : number/*float*//*GLfloat*/,
		y : number/*float*//*GLfloat*/,
		z : number/*float*//*GLfloat*/
	) : void;
	function uniform3fv(
		location : WebGLUniformLocation,
		v : Float32Array
	) : void;
	function uniform3fv(
		location : WebGLUniformLocation,
		v : number[]/*sequence<float>*/
	) : void;
	function uniform3i(
		location : WebGLUniformLocation,
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		z : int/*long*//*GLint*/
	) : void;
	function uniform3iv(
		location : WebGLUniformLocation,
		v : Int32Array
	) : void;
	function uniform3iv(
		location : WebGLUniformLocation,
		v : int[]/*sequence<long>*/
	) : void;
	function uniform3iv(
		location : WebGLUniformLocation,
		v : number[]
	) : void;
	function uniform4f(
		location : WebGLUniformLocation,
		x : number/*float*//*GLfloat*/,
		y : number/*float*//*GLfloat*/,
		z : number/*float*//*GLfloat*/,
		w : number/*float*//*GLfloat*/
	) : void;
	function uniform4fv(
		location : WebGLUniformLocation,
		v : Float32Array
	) : void;
	function uniform4fv(
		location : WebGLUniformLocation,
		v : number[]/*sequence<float>*/
	) : void;
	function uniform4i(
		location : WebGLUniformLocation,
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		z : int/*long*//*GLint*/,
		w : int/*long*//*GLint*/
	) : void;
	function uniform4iv(
		location : WebGLUniformLocation,
		v : Int32Array
	) : void;
	function uniform4iv(
		location : WebGLUniformLocation,
		v : int[]/*sequence<long>*/
	) : void;
	function uniform4iv(
		location : WebGLUniformLocation,
		v : number[]
	) : void;
	function uniformMatrix2fv(
		location : WebGLUniformLocation,
		transpose : boolean/*GLboolean*/,
		value : Float32Array
	) : void;
	function uniformMatrix2fv(
		location : WebGLUniformLocation,
		transpose : boolean/*GLboolean*/,
		value : number[]/*sequence<float>*/
	) : void;
	function uniformMatrix3fv(
		location : WebGLUniformLocation,
		transpose : boolean/*GLboolean*/,
		value : Float32Array
	) : void;
	function uniformMatrix3fv(
		location : WebGLUniformLocation,
		transpose : boolean/*GLboolean*/,
		value : number[]/*sequence<float>*/
	) : void;
	function uniformMatrix4fv(
		location : WebGLUniformLocation,
		transpose : boolean/*GLboolean*/,
		value : Float32Array
	) : void;
	function uniformMatrix4fv(
		location : WebGLUniformLocation,
		transpose : boolean/*GLboolean*/,
		value : number[]/*sequence<float>*/
	) : void;
	function useProgram(program : WebGLProgram) : void;
	function validateProgram(program : WebGLProgram) : void;
	function vertexAttrib1f(
		indx : int/*unsigned long*//*GLuint*/,
		x : number/*float*//*GLfloat*/
	) : void;
	function vertexAttrib1fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : Float32Array
	) : void;
	function vertexAttrib1fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : number[]/*sequence<float>*/
	) : void;
	function vertexAttrib2f(
		indx : int/*unsigned long*//*GLuint*/,
		x : number/*float*//*GLfloat*/,
		y : number/*float*//*GLfloat*/
	) : void;
	function vertexAttrib2fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : Float32Array
	) : void;
	function vertexAttrib2fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : number[]/*sequence<float>*/
	) : void;
	function vertexAttrib3f(
		indx : int/*unsigned long*//*GLuint*/,
		x : number/*float*//*GLfloat*/,
		y : number/*float*//*GLfloat*/,
		z : number/*float*//*GLfloat*/
	) : void;
	function vertexAttrib3fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : Float32Array
	) : void;
	function vertexAttrib3fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : number[]/*sequence<float>*/
	) : void;
	function vertexAttrib4f(
		indx : int/*unsigned long*//*GLuint*/,
		x : number/*float*//*GLfloat*/,
		y : number/*float*//*GLfloat*/,
		z : number/*float*//*GLfloat*/,
		w : number/*float*//*GLfloat*/
	) : void;
	function vertexAttrib4fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : Float32Array
	) : void;
	function vertexAttrib4fv(
		indx : int/*unsigned long*//*GLuint*/,
		values : number[]/*sequence<float>*/
	) : void;
	function vertexAttribPointer(
		indx : int/*unsigned long*//*GLuint*/,
		size : int/*long*//*GLint*/,
		type : int/*unsigned long*//*GLenum*/,
		normalized : boolean/*GLboolean*/,
		stride : int/*long*//*GLsizei*/,
		offset : number/*long long*//*GLintptr*/
	) : void;
	function viewport(
		x : int/*long*//*GLint*/,
		y : int/*long*//*GLint*/,
		width : int/*long*//*GLsizei*/,
		height : int/*long*//*GLsizei*/
	) : void;

} // end of WebGLRenderingContext

native class WebGLContextEvent extends Event {

	function constructor(type : string/*DOMString*/);
	function constructor(type : string/*DOMString*/, eventInit : WebGLContextEventInit);

	__readonly__ var statusMessage : string/*DOMString*/;

} // end of WebGLContextEvent

native class WebGLContextEventInit extends EventInit {

	var statusMessage : string/*DOMString*/;

} // end of WebGLContextEventInit

/*
end of generated files from:
	https://www.khronos.org/registry/webgl/specs/latest/webgl.idl
*/

