// THIS FILE IS AUTOMATICALLY GENERATED.
/**

XMLHttpReqeust Level 2

Specification:
    http://www.w3.org/TR/XMLHttpRequest/
*/

import "./dom.jsx";
import "./events.jsx";
import "./html.jsx";
import "./file.jsx";
import "./typedarray.jsx";

/*
automatically generated from:
	http://www.w3.org/TR/XMLHttpRequest/
*/
native __fake__ class XMLHttpRequestEventTarget extends EventTarget {

	// event handlers
	var onloadstart : function(:Event):void/*Function?*/;
	var onprogress : function(:Event):void/*Function?*/;
	var onabort : function(:Event):void/*Function?*/;
	var onerror : function(:Event):void/*Function?*/;
	var onload : function(:Event):void/*Function?*/;
	var ontimeout : function(:Event):void/*Function?*/;
	var onloadend : function(:Event):void/*Function?*/;

} // end of XMLHttpRequestEventTarget

native class XMLHttpRequestUpload extends XMLHttpRequestEventTarget {
}

native class XMLHttpRequest extends XMLHttpRequestEventTarget {

	function constructor();

	// event handler
	var onreadystatechange : function(:Event):void/*Function?*/;
	// states
	static const     UNSENT : int/*unsigned short*/;
	__readonly__ var UNSENT : int/*unsigned short*/;
	static const     OPENED : int/*unsigned short*/;
	__readonly__ var OPENED : int/*unsigned short*/;
	static const     HEADERS_RECEIVED : int/*unsigned short*/;
	__readonly__ var HEADERS_RECEIVED : int/*unsigned short*/;
	static const     LOADING : int/*unsigned short*/;
	__readonly__ var LOADING : int/*unsigned short*/;
	static const     DONE : int/*unsigned short*/;
	__readonly__ var DONE : int/*unsigned short*/;
	__readonly__ var readyState : int/*unsigned short*/;
	// request
	function open(
		method : string/*DOMString*/,
		url : string/*DOMString*/
	) : void;
	function open(
		method : string/*DOMString*/,
		url : string/*DOMString*/,
		async : boolean
	) : void;
	function open(
		method : string/*DOMString*/,
		url : string/*DOMString*/,
		async : boolean,
		user : string/*DOMString?*/
	) : void;
	function open(
		method : string/*DOMString*/,
		url : string/*DOMString*/,
		async : boolean,
		user : string/*DOMString?*/,
		password : string/*DOMString?*/
	) : void;
	function setRequestHeader(
		header : string/*DOMString*/,
		value : string/*DOMString*/
	) : void;
	var timeout : int/*unsigned long*/;
	var withCredentials : boolean;
	__readonly__ var upload : XMLHttpRequestUpload;
	function send() : void;
	function send(data : ArrayBuffer) : void;
	function send(data : Blob) : void;
	function send(data : Document) : void;
	function send(data : string/*DOMString?*/) : void;
	function send(data : FormData) : void;
	function abort() : void;
	// response
	__readonly__ var status : int/*unsigned short*/;
	__readonly__ var statusText : string/*DOMString*/;
	function getResponseHeader(
		header : string/*DOMString*/
	) : string/*DOMString*/;
	function getAllResponseHeaders() : string/*DOMString*/;
	function overrideMimeType(mime : string/*DOMString*/) : void;
	var responseType : string/*XMLHttpRequestResponseType*/;
	__readonly__ var response : variant/*any*/;
	__readonly__ var responseText : string/*DOMString*/;
	__readonly__ var responseXML : Document;

} // end of XMLHttpRequest

native class AnonXMLHttpRequest extends XMLHttpRequest {

	function constructor();

} // end of AnonXMLHttpRequest

native class FormData {

	function constructor();
	function constructor(form : HTMLFormElement);

	function append(name : string/*DOMString*/, value : Blob) : void;
	function append(
		name : string/*DOMString*/,
		value : Blob,
		filename : string/*DOMString*/
	) : void;
	function append(
		name : string/*DOMString*/,
		value : string/*DOMString*/
	) : void;

} // end of FormData

/*
end of generated files from:
	http://www.w3.org/TR/XMLHttpRequest/
*/

